import { useState, useEffect } from 'react';
import { HoloPanel } from '../components/primitives';
import { ScreenHeader } from '../components/shell';
import { CYAN, CYAN_BRIGHT, AMBER, VIOLET, JADE, ROSE, colorFor } from '../theme';
import { BRIEFINGS } from '../data/os-data';
import type { Briefing } from '../data/os-data';
import { LS, lsGet, lsSet, composeBriefing } from '../lib/claude';

/* -- Today Snapshot panel -- all real data -- */
function TodaySnapshot() {
  const runs   = lsGet<any[]>(LS.runs, []);
  const briefs = lsGet<any[]>(LS.briefings, []);
  const now    = new Date();
  const todayStr = now.toISOString().slice(0, 10);
  const timeStr  = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  const dateStr  = now.toLocaleDateString([], { weekday: 'long', month: 'short', day: 'numeric' });

  const runsToday     = runs.filter((r: any) => r.at?.startsWith(todayStr)).length;
  const contentBriefs = briefs.filter((b: any) => b.tag?.toLowerCase().includes('content')).length;

  const [mt5Ok, setMt5Ok] = useState<boolean | null>(null);
  useEffect(() => {
    fetch('http://localhost:1234/api/v1/rates?symbol=BTCUSD&tf=M1&n=1', {
      signal: AbortSignal.timeout(2000),
    }).then(r => setMt5Ok(r.ok)).catch(() => setMt5Ok(false));
  }, []);

  const utcH = now.getUTCHours();
  const contentWindow =
    utcH >= 11 && utcH < 14 ? 'THREAD - PEAK WINDOW NOW'   :
    utcH >= 15 && utcH < 18 ? 'VIDEO - PRIME TIME WINDOW'  :
    utcH >= 18 && utcH < 21 ? 'REEL - EVENING WINDOW'      :
                               'STAND-BY - NEXT: 12:00 UTC';
  const cwActive = (utcH >= 11 && utcH < 14) || (utcH >= 15 && utcH < 18) || (utcH >= 18 && utcH < 21);

  const SNAPS = [
    { label: 'AI RUNS TODAY',    value: String(runsToday),     sub: `${runs.length} total stored`,        color: CYAN   },
    { label: 'CONTENT BRIEFS',   value: String(contentBriefs), sub: `${briefs.length} briefings total`,   color: VIOLET },
    { label: 'TOTAL AI RUNS',    value: String(runs.length),   sub: 'all sessions',                       color: JADE   },
    { label: 'BRIEFINGS STORED', value: String(briefs.length), sub: 'persisted locally',                  color: AMBER  },
    {
      label: 'TRADER BOT',
      value: mt5Ok === null ? '...' : mt5Ok ? 'LIVE' : 'OFFLINE',
      sub:   mt5Ok ? 'MT5 bridge :1234' : 'Start MT5 bridge',
      color: mt5Ok ? JADE : ROSE,
    },
    { label: 'CLAUDE API',       value: 'READY',               sub: 'Configure in Setup',                  color: CYAN  },
  ];

  const infoRows = [
    {
      label: 'CONTENT WINDOW',
      value: contentWindow,
      color: cwActive ? JADE : VIOLET,
      detail: 'Based on UTC peak-engagement hours: 11-14 (thread), 15-18 (video), 18-21 (reel)',
    },
    {
      label: 'TRADER BOT STATUS',
      value: mt5Ok === null ? 'CHECKING...' : mt5Ok ? 'MT5 BRIDGE ACTIVE' : 'MT5 NOT CONNECTED',
      color: mt5Ok ? JADE : ROSE,
      detail: mt5Ok
        ? 'Zeus hooks active - real-time order book + positions'
        : 'Launch MT5 + ZeusBot bridge on port 1234 to activate trading',
    },
    {
      label: 'AI SESSIONS',
      value: `${runs.length} TOTAL RUNS`,
      color: CYAN,
      detail: `${runsToday} runs today - ${runs.length} runs stored in localStorage`,
    },
    {
      label: 'BRIEFINGS',
      value: briefs.length > 0 ? `${briefs.length} STORED` : 'NONE YET',
      color: briefs.length > 0 ? JADE : AMBER,
      detail: briefs.length > 0
        ? 'Generated by Claude - persisted locally'
        : 'Tap Morning Intel, Market Brief, or Custom Topic',
    },
  ];

  return (
    <HoloPanel label={`TODAY'S INTEL SNAPSHOT - ${dateStr}`} code={timeStr} status="live" style={{ flexShrink: 0 }}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 8, marginBottom: 12 }}>
        {SNAPS.map(s => (
          <div key={s.label} style={{ padding: '10px 10px', border: '1px solid var(--line-soft)', background: `${s.color}08`, borderTop: `2px solid ${s.color}` }}>
            <div className="hud-label" style={{ fontSize: 7.5, color: 'var(--cyan-dim)', letterSpacing: '0.18em', marginBottom: 4 }}>{s.label}</div>
            <div className="font-display" style={{ fontSize: 18, color: s.color, lineHeight: 1 }}>{s.value}</div>
            <div className="font-mono" style={{ fontSize: 8, color: 'var(--cyan-dim)', marginTop: 3 }}>{s.sub}</div>
          </div>
        ))}
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
        {infoRows.map(item => (
          <div key={item.label} style={{ display: 'flex', gap: 10, padding: '10px 12px', border: `1px solid ${item.color}30`, background: `${item.color}06`, alignItems: 'center' }}>
            <div style={{ flex: 1 }}>
              <div className="hud-label" style={{ fontSize: 8, color: item.color, letterSpacing: '0.22em', marginBottom: 3 }}>{item.label}</div>
              <div className="font-mono" style={{ fontSize: 11, color: 'var(--fg)', lineHeight: 1.3 }}>{item.value}</div>
              <div className="font-mono" style={{ fontSize: 9, color: 'var(--cyan-dim)', marginTop: 2 }}>{item.detail}</div>
            </div>
            <div style={{ width: 6, height: 6, borderRadius: 99, background: item.color, flexShrink: 0, boxShadow: `0 0 8px ${item.color}` }} />
          </div>
        ))}
      </div>
    </HoloPanel>
  );
}

function BriefingCard({ b }: { b: Briefing }) {
  const accent = colorFor(b.accent);
  return (
    <div className="holo holo-brackets anim-fade-up" style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 8 }}>
      <span className="br-bl" /><span className="br-br" />
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <div className="hud-label" style={{ fontSize: 9, color: accent, letterSpacing: '0.4em' }}>@ {b.tag} - {b.time}</div>
          <div className="font-display glow-cyan" style={{ fontSize: 14, color: CYAN_BRIGHT, marginTop: 6, lineHeight: 1.2 }}>{b.title}</div>
        </div>
        <div className="font-mono" style={{ fontSize: 8.5, color: 'var(--cyan-dim)' }}>{b.id}</div>
      </div>
      <div className="font-mono" style={{ fontSize: 10.5, color: 'var(--cyan-dim)', lineHeight: 1.5 }}>{b.blurb}</div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
        {(b.items || []).map((it, i) => (
          <div key={i} style={{ display: 'grid', gridTemplateColumns: '60px 1fr', gap: 8, alignItems: 'start' }}>
            <span className="hud-label" style={{ fontSize: 8.5, color: CYAN_BRIGHT, letterSpacing: '0.18em', padding: '2px 4px', border: `1px solid ${accent}55`, textAlign: 'center' }}>{it.tag}</span>
            <span className="font-mono" style={{ fontSize: 10.5, color: 'var(--fg)', lineHeight: 1.4 }}>{it.text}</span>
          </div>
        ))}
      </div>
      {b.summary && (
        <div style={{ padding: 10, border: `1px solid ${accent}55`, background: `oklch(0.78 0.13 215 / 0.04)` }}>
          <div className="hud-label" style={{ fontSize: 8.5, color: accent, letterSpacing: '0.32em' }}>EMPFEHLUNG</div>
          <div className="font-mono" style={{ fontSize: 10.5, color: 'var(--fg)', marginTop: 4, lineHeight: 1.4 }}>{b.summary}</div>
        </div>
      )}
    </div>
  );
}

type Kind = 'morning' | 'market' | 'content' | 'custom';

export default function BriefingsScreen() {
  const [live, setLive] = useState<Briefing[]>(() => lsGet<Briefing[]>(LS.briefings, []));
  const [busy, setBusy] = useState<Kind | null>(null);
  const [error, setError] = useState('');
  const [extra, setExtra] = useState('');
  const [schedHour, setSchedHour] = useState<string>(() => localStorage.getItem('jarvis.briefing.hour') || '');
  const [schedKind, setSchedKind] = useState<Kind>('morning');
  const [schedEnabled, setSchedEnabled] = useState(() => localStorage.getItem('jarvis.briefing.enabled') === '1');
  const [schedStatus, setSchedStatus] = useState('');

  // Client-side scheduler: check every minute if it's time to auto-generate
  useEffect(() => {
    if (!schedEnabled || !schedHour) return;
    const tick = setInterval(async () => {
      const now = new Date();
      const [hh, mm] = schedHour.split(':').map(Number);
      if (now.getHours() === hh && now.getMinutes() === mm) {
        const lastRun = localStorage.getItem('jarvis.briefing.lastrun');
        const today = now.toDateString();
        if (lastRun === today) return; // already ran today
        localStorage.setItem('jarvis.briefing.lastrun', today);
        await gen(schedKind);
      }
    }, 60000);
    return () => clearInterval(tick);
  }, [schedEnabled, schedHour, schedKind]);

  function saveSchedule() {
    localStorage.setItem('jarvis.briefing.hour', schedHour);
    localStorage.setItem('jarvis.briefing.enabled', schedEnabled ? '1' : '0');
    setSchedStatus(schedEnabled && schedHour ? `Scheduled: ${schedKind} @ ${schedHour} daily` : 'Schedule cleared');
    setTimeout(() => setSchedStatus(''), 3000);
  }

  async function gen(kind: Kind) {
    setBusy(kind); setError('');
    try {
      const b = await composeBriefing(kind, extra);
      const next = [b, ...live].slice(0, 12);
      setLive(next);
      lsSet(LS.briefings, next);
    } catch (e: any) { setError(String(e?.message || e)); }
    setBusy(null);
  }

  function remove(id: string) {
    const next = live.filter(b => b.id !== id);
    setLive(next);
    lsSet(LS.briefings, next);
  }

  const KINDS: { id: Kind; label: string; color: string }[] = [
    { id: 'morning', label: 'Morning Intel', color: CYAN   },
    { id: 'market',  label: 'Market Brief',  color: AMBER  },
    { id: 'content', label: 'Content Brief', color: VIOLET },
    { id: 'custom',  label: 'Custom Topic',  color: JADE   },
  ];

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', gap: 12, minHeight: 0 }}>
      <ScreenHeader
        tag="BRIEFINGS"
        title="ON-DEMAND INTELLIGENCE"
        subtitle="Generate a live briefing in 3-8 seconds. Stored locally. Use Custom Topic for anything ad-hoc."
      />

      <TodaySnapshot />

      {/* ── Auto-Schedule Panel ────────────────────────────────────── */}
      <HoloPanel label="AUTO-SCHEDULE" code="SCHED" status={schedEnabled ? 'live' : 'idle'}>
        <div style={{ display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
          <span className="hud-label" style={{ fontSize: 8, color: 'rgba(255,255,255,0.4)', letterSpacing: '0.18em' }}>DAILY TIME</span>
          <input type="time" value={schedHour} onChange={e => setSchedHour(e.target.value)}
            style={{ padding: '4px 8px', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.12)', color: 'rgba(255,255,255,0.75)', fontFamily: 'JetBrains Mono', fontSize: 11, outline: 'none' }} />
          <span className="hud-label" style={{ fontSize: 8, color: 'rgba(255,255,255,0.4)', letterSpacing: '0.18em' }}>TYPE</span>
          <div style={{ display: 'flex', gap: 4 }}>
            {(['morning','market','content','custom'] as Kind[]).map(k => (
              <button key={k} onClick={() => setSchedKind(k)} className="hud-label"
                style={{ padding: '3px 9px', fontSize: 8, cursor: 'pointer', letterSpacing: '0.1em',
                  border: `1px solid ${schedKind===k ? CYAN : 'rgba(255,255,255,0.1)'}`,
                  color: schedKind===k ? CYAN : 'rgba(255,255,255,0.35)',
                  background: schedKind===k ? 'rgba(0,229,255,0.08)' : 'transparent' }}>
                {k.toUpperCase()}
              </button>
            ))}
          </div>
          <button onClick={() => { setSchedEnabled(v => !v); }} className="hud-label"
            style={{ padding: '4px 10px', fontSize: 8, cursor: 'pointer', letterSpacing: '0.14em',
              border: `1px solid ${schedEnabled ? JADE : 'rgba(255,255,255,0.15)'}`,
              color: schedEnabled ? JADE : 'rgba(255,255,255,0.4)',
              background: schedEnabled ? 'rgba(0,208,132,0.08)' : 'transparent' }}>
            {schedEnabled ? '● ENABLED' : '○ DISABLED'}
          </button>
          <button onClick={saveSchedule} className="hud-label"
            style={{ padding: '4px 12px', fontSize: 8, cursor: 'pointer', letterSpacing: '0.14em', color: AMBER, border: `1px solid ${AMBER}55`, background: 'transparent' }}>
            SAVE
          </button>
          {schedStatus && <span className="font-mono" style={{ fontSize: 9, color: JADE, marginLeft: 4 }}>{schedStatus}</span>}
        </div>
      </HoloPanel>

      <HoloPanel label="COMPOSE NEW BRIEFING - LIVE" code="GEN" status="live">
        <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
          <div style={{ flex: 1 }}>
            <div className="hud-label" style={{ fontSize: 9, color: 'var(--cyan-dim)', letterSpacing: '0.32em', marginBottom: 6 }}>FOCUS / EXTRA CONTEXT (OPTIONAL)</div>
            <textarea
              value={extra}
              onChange={e => setExtra(e.target.value)}
              placeholder="e.g. 'Crypto + DAX, plus Berlin Startup News'"
              style={{ width: '100%', height: 60, background: 'oklch(0.06 0.014 240 / 0.6)', border: '1px solid var(--line)', color: 'var(--fg)', padding: 10, fontFamily: 'JetBrains Mono', fontSize: 11, lineHeight: 1.4, resize: 'none', outline: 'none' }}
            />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6, minWidth: 220 }}>
            {KINDS.map(k => (
              <button
                key={k.id}
                onClick={() => gen(k.id)}
                disabled={!!busy}
                className="hud-label"
                style={{
                  padding: '10px 12px', fontSize: 10, letterSpacing: '0.28em',
                  color: busy === k.id ? 'var(--cyan-dim)' : CYAN_BRIGHT,
                  border: `1px solid ${k.color}80`,
                  background: busy === k.id ? 'oklch(0.78 0.13 215 / 0.18)' : 'transparent',
                  cursor: busy ? 'wait' : 'pointer',
                  textShadow: busy ? 'none' : `0 0 6px ${k.color}`,
                  textAlign: 'left',
                  display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 6,
                }}
              >
                <span>{k.label.toUpperCase()}</span>
                <span style={{ fontSize: 11 }}>{busy === k.id ? 'O' : '>'}</span>
              </button>
            ))}
          </div>
        </div>
        {error && <div className="font-mono" style={{ fontSize: 10, color: AMBER, marginTop: 8 }}>! {error}</div>}
      </HoloPanel>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, flex: 1, minHeight: 0, overflow: 'auto' }} className="nx-scroll">
        {live.map(b => (
          <div key={b.id} style={{ position: 'relative' }}>
            <button
              onClick={() => remove(b.id)}
              className="hud-label"
              style={{ position: 'absolute', top: 8, right: 8, padding: '4px 8px', fontSize: 8.5, color: 'var(--cyan-dim)', border: '1px solid var(--line-soft)', letterSpacing: '0.22em', zIndex: 2 }}
            >X</button>
            <BriefingCard b={b} />
          </div>
        ))}

        {live.length === 0 && BRIEFINGS.length === 0 && (
          <div style={{ gridColumn: '1 / -1', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, padding: 48, border: '1px dashed rgba(0,229,255,0.15)', background: 'rgba(0,229,255,0.02)' }}>
            <div className="hud-label" style={{ fontSize: 10, color: CYAN, letterSpacing: '0.4em' }}>NO BRIEFINGS YET</div>
            <div className="font-mono" style={{ fontSize: 11, color: 'var(--cyan-dim)', textAlign: 'center', maxWidth: 400, lineHeight: 1.6 }}>
              Click <strong style={{ color: CYAN_BRIGHT }}>Morning Intel</strong>, <strong style={{ color: AMBER }}>Market Brief</strong>,{' '}
              <strong style={{ color: VIOLET }}>Content Brief</strong>, or <strong style={{ color: JADE }}>Custom Topic</strong> above to generate your first live briefing with Claude AI.
            </div>
            <div className="font-mono" style={{ fontSize: 9, color: 'rgba(255,255,255,0.2)', letterSpacing: '0.2em' }}>BRIEFINGS ARE STORED IN LOCALSTORAGE - PERSIST ACROSS SESSIONS</div>
          </div>
        )}

        {live.length === 0 && BRIEFINGS.map(b => <BriefingCard key={b.id} b={b} />)}
      </div>
    </div>
  );
}