// @ts-nocheck
// The curated workflow template catalogue. Split into its own module because it
// is pure data and by far the bulk of the old monolith — and because both the
// screen header and the builder tab read WF_TEMPLATES, so it cannot live inside
// either one without coupling them together.
import type { WorkflowNode } from '../../data/os-data';
import type { TplDef } from './types';

// Shorthand helpers for template definitions
const _n = (id: string, x: number, y: number, label: string, team: string): WorkflowNode => ({
  id,
  x,
  y,
  label,
  team,
});
const _e = (...pairs: [string, string][]): [string, string][] => pairs;

export const WF_TEMPLATES: TplDef[] = [
  // ── CI/CD & DevOps (8) ──────────────────────────────────────────────────
  {
    id: 'TPL-001',
    category: 'CI/CD',
    source: 'github',
    owner: 'INF-FS',
    name: 'Full-Stack CI/CD Pipeline',
    trigger: 'Push · main / PR',
    tags: ['github-actions', 'docker', 'deploy', 'testing'],
    desc: 'Unit test + lint in parallel → Docker build → Stage deploy → Smoke test → Prod deploy → Slack notify.',
    nodes: [
      _n('n1', 60, 100, 'Push · Trigger', 'INF-FS'),
      _n('n2', 260, 40, 'Test · Unit + Int', 'INF-FS'),
      _n('n3', 260, 150, 'Lint · Type Check', 'INF-FS'),
      _n('n4', 460, 100, 'Build · Docker', 'INF-FS'),
      _n('n5', 640, 100, 'Deploy · Staging', 'INF-WEB'),
      _n('n6', 820, 50, 'Smoke Test', 'INF-FS'),
      _n('n7', 820, 150, 'Deploy · Prod', 'INF-WEB'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n2', 'n4'],
      ['n3', 'n4'],
      ['n4', 'n5'],
      ['n5', 'n6'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-002',
    category: 'CI/CD',
    source: 'github',
    owner: 'INF-FS',
    name: 'PR Auto-Review Bot',
    trigger: 'PR Opened',
    tags: ['github-actions', 'AI-review', 'code-quality'],
    desc: 'Static analysis + AI code review in parallel → post review comment → set merge status check.',
    nodes: [
      _n('n1', 60, 100, 'PR Opened', 'INF-FS'),
      _n('n2', 260, 50, 'Static Analysis', 'INF-FS'),
      _n('n3', 260, 150, 'AI Code Review', 'ARC-OPT'),
      _n('n4', 480, 100, 'Merge Comment', 'INF-FS'),
      _n('n5', 680, 100, 'Status Check Gate', 'INF-FS'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5']),
  },
  {
    id: 'TPL-003',
    category: 'CI/CD',
    source: 'github',
    owner: 'INF-HCK',
    name: 'Security Scan Gate',
    trigger: 'Push · any branch',
    tags: ['SAST', 'DAST', 'SCA', 'security'],
    desc: 'SAST + DAST + SCA dependency scan in parallel → aggregate findings → fail gate if critical → JIRA ticket.',
    nodes: [
      _n('n1', 60, 100, 'Push Trigger', 'INF-HCK'),
      _n('n2', 260, 30, 'SAST · CodeQL', 'INF-HCK'),
      _n('n3', 260, 100, 'DAST · ZAP Scan', 'INF-HCK'),
      _n('n4', 260, 170, 'SCA · Dependency', 'INF-HCK'),
      _n('n5', 500, 100, 'Aggregate Findings', 'INF-HCK'),
      _n('n6', 700, 100, 'Severity Gate', 'INF-HCK'),
      _n('n7', 860, 100, 'JIRA · Auto Ticket', 'INF-FS'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n1', 'n4'],
      ['n2', 'n5'],
      ['n3', 'n5'],
      ['n4', 'n5'],
      ['n5', 'n6'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-004',
    category: 'CI/CD',
    source: 'github',
    owner: 'INF-FS',
    name: 'Semantic Release Pipeline',
    trigger: 'Merge to main',
    tags: ['semver', 'changelog', 'npm', 'release'],
    desc: 'Analyze commits (Conventional Commits) → bump version → generate CHANGELOG → publish → tag → notify.',
    nodes: [
      _n('n1', 60, 100, 'Merge · main', 'INF-FS'),
      _n('n2', 240, 100, 'Analyze Commits', 'INF-FS'),
      _n('n3', 420, 100, 'Bump Version · SemVer', 'INF-FS'),
      _n('n4', 600, 50, 'Generate CHANGELOG', 'INF-FS'),
      _n('n5', 600, 150, 'Publish · npm/PyPI', 'INF-FS'),
      _n('n6', 800, 100, 'Git Tag + Notify', 'INF-FS'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-005',
    category: 'CI/CD',
    source: 'n8n',
    owner: 'INF-FS',
    name: 'Infra Drift Detection',
    trigger: 'Schedule · 1h',
    tags: ['terraform', 'IaC', 'drift', 'ops'],
    desc: 'Run terraform plan → compare with last known state → detect drift → auto-open ticket → trigger remediation.',
    nodes: [
      _n('n1', 60, 100, 'Schedule · 1h', 'INF-FS'),
      _n('n2', 240, 100, 'Terraform Plan', 'INF-FS'),
      _n('n3', 440, 100, 'Drift Compare', 'INF-FS'),
      _n('n4', 640, 50, 'Alert · Slack', 'ARC-OPT'),
      _n('n5', 640, 150, 'JIRA Ticket', 'INF-FS'),
      _n('n6', 820, 100, 'Auto Remediate', 'INF-FS'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-006',
    category: 'CI/CD',
    source: 'github',
    owner: 'INF-WEB',
    name: 'Blue/Green Deployment',
    trigger: 'Tag · v*.*.*',
    tags: ['zero-downtime', 'kubernetes', 'blue-green'],
    desc: 'Build image → deploy to Green slot → run smoke tests → health checks → swap DNS → warm Green → retire Blue.',
    nodes: [
      _n('n1', 60, 100, 'Tag · Release', 'INF-WEB'),
      _n('n2', 240, 100, 'Build Image', 'INF-FS'),
      _n('n3', 420, 100, 'Deploy · Green', 'INF-WEB'),
      _n('n4', 600, 50, 'Smoke Tests', 'INF-FS'),
      _n('n5', 600, 150, 'Health Checks', 'INF-WEB'),
      _n('n6', 780, 100, 'Swap DNS · Route', 'INF-WEB'),
      _n('n7', 860, 100, 'Retire Blue', 'INF-WEB'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n3', 'n4'],
      ['n3', 'n5'],
      ['n4', 'n6'],
      ['n5', 'n6'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-007',
    category: 'CI/CD',
    source: 'n8n',
    owner: 'INF-FS',
    name: 'Auto Rollback Trigger',
    trigger: 'Error Rate > 1%',
    tags: ['monitoring', 'rollback', 'SRE', 'ops'],
    desc: 'Monitor error spike → fetch canary metrics → compare baseline → decide rollback → execute → page on-call.',
    nodes: [
      _n('n1', 60, 100, 'Monitor · Error %', 'INF-FS'),
      _n('n2', 260, 100, 'Fetch Canary Metrics', 'INF-FS'),
      _n('n3', 460, 100, 'Compare Baseline', 'ARC-OPT'),
      _n('n4', 640, 100, 'Decide: Rollback?', 'ARC-OPT'),
      _n('n5', 820, 50, 'Execute Rollback', 'INF-WEB'),
      _n('n6', 820, 150, 'Page On-Call', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-008',
    category: 'CI/CD',
    source: 'github',
    owner: 'INF-SC',
    name: 'Multi-Cloud Sync Pipeline',
    trigger: 'File change · S3',
    tags: ['aws', 'gcp', 'azure', 'multi-cloud'],
    desc: 'Detect change in S3 → validate → replicate to GCS + Azure Blob in parallel → checksum verify → log.',
    nodes: [
      _n('n1', 60, 100, 'S3 Event · Change', 'INF-SC'),
      _n('n2', 240, 100, 'Validate Payload', 'INF-SC'),
      _n('n3', 420, 50, 'Replicate · GCS', 'INF-SC'),
      _n('n4', 420, 150, 'Replicate · Azure', 'INF-SC'),
      _n('n5', 640, 100, 'Checksum Verify', 'INF-SC'),
      _n('n6', 820, 100, 'Log · Audit Trail', 'INF-SC'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },

  // ── Content & Social (8) ────────────────────────────────────────────────
  {
    id: 'TPL-009',
    category: 'CONTENT',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Content Repurpose Engine',
    trigger: 'YouTube Publish Event',
    tags: ['repurpose', 'AI', 'multi-platform', 'content'],
    desc: 'One video publish triggers 4 parallel rewrite agents: X thread, IG caption, newsletter snippet, LinkedIn post → schedule all.',
    nodes: [
      _n('n1', 60, 110, 'YT Publish Event', 'CNT-YT'),
      _n('n2', 260, 30, 'X Thread · AI', 'CNT-X'),
      _n('n3', 260, 90, 'IG Caption · AI', 'CNT-IG'),
      _n('n4', 260, 150, 'Newsletter · AI', 'CNT-NWS'),
      _n('n5', 260, 210, 'Twitch Highlight', 'CNT-TW'),
      _n('n6', 520, 120, 'Schedule · All', 'CNT-HUB'),
      _n('n7', 720, 120, 'Publish Queue', 'CNT-HUB'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n1', 'n4'],
      ['n1', 'n5'],
      ['n2', 'n6'],
      ['n3', 'n6'],
      ['n4', 'n6'],
      ['n5', 'n6'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-010',
    category: 'CONTENT',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'SEO Content Pipeline',
    trigger: 'Keyword Brief Input',
    tags: ['SEO', 'content-writing', 'AI', 'publish'],
    desc: 'Keyword → SERP research → AI brief → AI draft → SEO optimize → human review gate → publish → rank track.',
    nodes: [
      _n('n1', 60, 100, 'Keyword Input', 'CNT-HUB'),
      _n('n2', 230, 100, 'SERP Research', 'ARC-SCT'),
      _n('n3', 400, 100, 'AI · Brief Gen', 'ARC-OPT'),
      _n('n4', 570, 100, 'AI · Draft', 'ARC-FRG'),
      _n('n5', 720, 50, 'SEO Optimize', 'CNT-HUB'),
      _n('n6', 720, 150, 'Human Review', 'CNT-HUB'),
      _n('n7', 880, 100, 'Publish + Track', 'CNT-HUB'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n3', 'n4'],
      ['n4', 'n5'],
      ['n4', 'n6'],
      ['n5', 'n7'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-011',
    category: 'CONTENT',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Social Media Scheduler',
    trigger: 'Content Calendar · Daily',
    tags: ['scheduling', 'social', 'automation', 'buffer'],
    desc: 'Pull content calendar → classify platform → approval gate → enqueue → multi-platform publish → analytics collect.',
    nodes: [
      _n('n1', 60, 100, 'Calendar Pull', 'CNT-HUB'),
      _n('n2', 240, 100, 'Classify Platform', 'CNT-HUB'),
      _n('n3', 420, 100, 'Approval Gate', 'CNT-HUB'),
      _n('n4', 600, 100, 'Enqueue Posts', 'CNT-HUB'),
      _n('n5', 780, 100, 'Publish · All', 'CNT-HUB'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5']),
  },
  {
    id: 'TPL-012',
    category: 'CONTENT',
    source: 'n8n',
    owner: 'CNT-NWS',
    name: 'Newsletter Automation',
    trigger: 'Weekly · Monday 08:00',
    tags: ['newsletter', 'email', 'beehiiv', 'AI'],
    desc: 'Collect top stories → AI summarize → generate issue → add trade idea section → design → send → analytics.',
    nodes: [
      _n('n1', 60, 100, 'Trigger · Mon 08:00', 'CNT-NWS'),
      _n('n2', 240, 50, 'Fetch Top Stories', 'ARC-SCT'),
      _n('n3', 240, 150, 'Pull Trade Idea', 'FIN-TRD'),
      _n('n4', 460, 100, 'AI · Compose Issue', 'ARC-FRG'),
      _n('n5', 640, 100, 'Design · HTML', 'CNT-NWS'),
      _n('n6', 820, 100, 'Send + Analytics', 'CNT-NWS'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-013',
    category: 'CONTENT',
    source: 'n8n',
    owner: 'CNT-YT',
    name: 'YouTube Upload Flow',
    trigger: 'Render Complete Event',
    tags: ['youtube', 'thumbnail', 'SEO', 'metadata'],
    desc: 'Video render done → AI generate thumbnail variants → SEO metadata → upload → cards + endscreens → notify.',
    nodes: [
      _n('n1', 60, 100, 'Render Complete', 'CNT-YT'),
      _n('n2', 240, 50, 'AI · Thumbnail × 3', 'ARC-FRG'),
      _n('n3', 240, 150, 'SEO Metadata · AI', 'CNT-YT'),
      _n('n4', 460, 100, 'Upload · YouTube', 'CNT-YT'),
      _n('n5', 640, 100, 'Cards + End Screen', 'CNT-YT'),
      _n('n6', 820, 100, 'Notify · Telegram', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-014',
    category: 'CONTENT',
    source: 'jarvis',
    owner: 'CNT-X',
    name: 'Viral Thread Machine',
    trigger: 'Trend Detected',
    tags: ['X', 'thread', 'viral', 'AI-writing'],
    desc: 'Detect trending topic → score relevance → AI generate hook + 8 tweets + CTA → schedule → post → monitor engagement.',
    nodes: [
      _n('n1', 60, 100, 'Trend Detect · API', 'ARC-SCT'),
      _n('n2', 260, 100, 'Score Relevance', 'ARC-OPT'),
      _n('n3', 460, 100, 'AI · Thread Write', 'ARC-FRG'),
      _n('n4', 640, 50, 'Schedule Optimal', 'CNT-X'),
      _n('n5', 640, 150, 'Post · X API', 'CNT-X'),
      _n('n6', 820, 100, 'Monitor Engagement', 'CNT-X'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-015',
    category: 'CONTENT',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Podcast → Multi-Platform',
    trigger: 'Episode Upload',
    tags: ['podcast', 'transcription', 'repurpose', 'clips'],
    desc: 'Upload audio → transcribe (Whisper) → extract clips → blog post → show notes → social snippets → publish all.',
    nodes: [
      _n('n1', 60, 100, 'Episode Upload', 'CNT-HUB'),
      _n('n2', 240, 100, 'Transcribe · Whisper', 'ARC-OPT'),
      _n('n3', 440, 30, 'Extract Clips · AI', 'ARC-FRG'),
      _n('n4', 440, 100, 'Blog Post · AI', 'CNT-NWS'),
      _n('n5', 440, 170, 'Show Notes · AI', 'CNT-HUB'),
      _n('n6', 680, 100, 'Publish All', 'CNT-HUB'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n2', 'n4'],
      ['n2', 'n5'],
      ['n3', 'n6'],
      ['n4', 'n6'],
      ['n5', 'n6'],
    ),
  },
  {
    id: 'TPL-016',
    category: 'CONTENT',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Brand Monitor + Response',
    trigger: 'Continuous · 5min',
    tags: ['brand', 'monitoring', 'sentiment', 'social-listening'],
    desc: 'Listen mentions → classify intent → sentiment score → AI draft response → human approval gate → post reply.',
    nodes: [
      _n('n1', 60, 100, 'Listen · Mentions', 'CNT-HUB'),
      _n('n2', 240, 100, 'Classify Intent', 'ARC-OPT'),
      _n('n3', 420, 100, 'Sentiment Score', 'ARC-OPT'),
      _n('n4', 600, 100, 'AI Draft Response', 'ARC-FRG'),
      _n('n5', 780, 100, 'Human Approval', 'CNT-HUB'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5']),
  },

  // ── Trading & Finance (6) ────────────────────────────────────────────────
  {
    id: 'TPL-017',
    category: 'TRADING',
    source: 'jarvis',
    owner: 'FIN-TRD',
    name: 'Market Scanner · Signals',
    trigger: 'Tick · Real-time',
    tags: ['screener', 'signals', 'alerts', 'trading'],
    desc: 'Screener → signal detection (momentum + mean-rev) → filter noise → score → alert Telegram → log to DB.',
    nodes: [
      _n('n1', 60, 100, 'Tick · Screener', 'FIN-BOT'),
      _n('n2', 260, 50, 'Signal · Momentum', 'FIN-TRD'),
      _n('n3', 260, 150, 'Signal · Mean-Rev', 'FIN-TRD'),
      _n('n4', 480, 100, 'Filter + Score', 'ARC-OPT'),
      _n('n5', 660, 50, 'Alert · Telegram', 'ARC-OPT'),
      _n('n6', 660, 150, 'Log · Database', 'INF-FS'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-018',
    category: 'TRADING',
    source: 'jarvis',
    owner: 'FIN-TRD',
    name: 'Risk Report Automation',
    trigger: 'Daily 17:00 Close',
    tags: ['risk', 'VaR', 'reporting', 'pdf'],
    desc: 'Pull positions at close → calculate VaR + drawdown + exposure → AI risk narrative → PDF generate → email CFO.',
    nodes: [
      _n('n1', 60, 100, 'Market Close', 'FIN-BOT'),
      _n('n2', 240, 100, 'Pull Positions', 'FIN-TRD'),
      _n('n3', 440, 100, 'Calculate VaR + DD', 'FIN-TRD'),
      _n('n4', 640, 100, 'AI Risk Narrative', 'ARC-OPT'),
      _n('n5', 820, 100, 'PDF + Email CFO', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5']),
  },
  {
    id: 'TPL-019',
    category: 'TRADING',
    source: 'jarvis',
    owner: 'FIN-TRD',
    name: 'Portfolio Rebalancer',
    trigger: 'Drift Threshold > 5%',
    tags: ['rebalancing', 'portfolio', 'execution'],
    desc: 'Detect drift → compute target weights → calculate trades → risk check → execute orders → confirm + notify.',
    nodes: [
      _n('n1', 60, 100, 'Drift Detect > 5%', 'FIN-TRD'),
      _n('n2', 240, 100, 'Compute Weights', 'FIN-TRD'),
      _n('n3', 420, 100, 'Calc Trade List', 'FIN-TRD'),
      _n('n4', 600, 100, 'Risk Gate · VaR', 'ARC-OPT'),
      _n('n5', 780, 50, 'Execute Orders', 'FIN-BOT'),
      _n('n6', 780, 150, 'Confirm + Notify', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-020',
    category: 'TRADING',
    source: 'jarvis',
    owner: 'FIN-BOT',
    name: 'DCA Bot Pipeline',
    trigger: 'Schedule · Weekly',
    tags: ['DCA', 'BTC', 'automation', 'crypto'],
    desc: 'Weekly trigger → check current price vs 20w MA → calculate DCA size → execute buy → log → update dashboard.',
    nodes: [
      _n('n1', 60, 100, 'Weekly Trigger', 'FIN-BOT'),
      _n('n2', 240, 100, 'Price vs 20W MA', 'FIN-TRD'),
      _n('n3', 420, 100, 'Calc DCA Size', 'FIN-TRD'),
      _n('n4', 600, 100, 'Execute Buy', 'FIN-BOT'),
      _n('n5', 780, 100, 'Log + Dashboard', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5']),
  },
  {
    id: 'TPL-021',
    category: 'TRADING',
    source: 'n8n',
    owner: 'FIN-TRD',
    name: 'Earnings Alert System',
    trigger: 'Pre-market · Earnings Watch',
    tags: ['earnings', 'research', 'alerts', 'fundamental'],
    desc: 'Detect earnings event → scrape filing + analyst estimates → AI research brief → format → Telegram alert → archive.',
    nodes: [
      _n('n1', 60, 100, 'Earnings Watch', 'FIN-TRD'),
      _n('n2', 240, 50, 'Scrape 8-K Filing', 'INF-WS'),
      _n('n3', 240, 150, 'Analyst Estimates', 'INF-WS'),
      _n('n4', 460, 100, 'AI Research Brief', 'ARC-OPT'),
      _n('n5', 660, 100, 'Alert + Archive', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5']),
  },
  {
    id: 'TPL-022',
    category: 'TRADING',
    source: 'jarvis',
    owner: 'FIN-TRD',
    name: 'Options Flow Monitor',
    trigger: 'Stream · Unusual Whales',
    tags: ['options', 'dark-pool', 'flow', 'alert'],
    desc: 'Stream unusual options flow → filter by size > $1M + DTE < 21 → score sentiment → alert with context.',
    nodes: [
      _n('n1', 60, 100, 'Flow Stream', 'FIN-TRD'),
      _n('n2', 260, 100, 'Filter · Size+DTE', 'FIN-TRD'),
      _n('n3', 460, 100, 'Sentiment Score', 'ARC-OPT'),
      _n('n4', 660, 50, 'Alert · Telegram', 'ARC-OPT'),
      _n('n5', 660, 150, 'Log + Backfill', 'FIN-BOT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5']),
  },

  // ── AI & ML (6) ─────────────────────────────────────────────────────────
  {
    id: 'TPL-023',
    category: 'AI/ML',
    source: 'github',
    owner: 'ARC-FRG',
    name: 'RAG Pipeline Builder',
    trigger: 'Document Ingest',
    tags: ['RAG', 'embeddings', 'vector-db', 'langchain'],
    desc: 'Ingest docs → chunk + clean → embed (OpenAI/Cohere) → upsert Pinecone/Qdrant → query → rerank → respond.',
    nodes: [
      _n('n1', 60, 100, 'Doc Ingest', 'INF-WS'),
      _n('n2', 240, 100, 'Chunk + Clean', 'ARC-FRG'),
      _n('n3', 420, 100, 'Embed · OpenAI', 'ARC-FRG'),
      _n('n4', 600, 100, 'Upsert · Pinecone', 'INF-SC'),
      _n('n5', 780, 50, 'Query + Rerank', 'ARC-OPT'),
      _n('n6', 780, 150, 'Generate Response', 'ARC-FRG'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-024',
    category: 'AI/ML',
    source: 'github',
    owner: 'ARC-FRG',
    name: 'Model Fine-Tune Pipeline',
    trigger: 'Dataset Ready Event',
    tags: ['fine-tuning', 'LoRA', 'eval', 'MLflow'],
    desc: 'Dataset → validate + dedupe → train (LoRA/QLoRA) → evaluate vs baseline → compare evals → promote if better.',
    nodes: [
      _n('n1', 60, 100, 'Dataset Ready', 'INF-SC'),
      _n('n2', 240, 100, 'Validate + Dedupe', 'ARC-FRG'),
      _n('n3', 440, 100, 'Train · LoRA', 'INF-SC'),
      _n('n4', 640, 50, 'Eval · Benchmarks', 'ARC-FRG'),
      _n('n5', 640, 150, 'Eval · Baseline', 'ARC-FRG'),
      _n('n6', 820, 100, 'Promote if Better', 'ARC-FRG'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-025',
    category: 'AI/ML',
    source: 'github',
    owner: 'ARC-OPT',
    name: 'LLM Eval Harness',
    trigger: 'Model Version Change',
    tags: ['evals', 'LLM', 'benchmarks', 'CI'],
    desc: 'Run test prompts through new + old model → score with judge LLM → aggregate → generate report → fail if regressed.',
    nodes: [
      _n('n1', 60, 100, 'Model Version Bump', 'ARC-FRG'),
      _n('n2', 240, 50, 'Run New Model', 'INF-SC'),
      _n('n3', 240, 150, 'Run Old Model', 'INF-SC'),
      _n('n4', 460, 100, 'Judge · LLM Score', 'ARC-OPT'),
      _n('n5', 640, 100, 'Aggregate + Report', 'ARC-OPT'),
      _n('n6', 820, 100, 'Gate: Pass/Fail', 'ARC-FRG'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-026',
    category: 'AI/ML',
    source: 'n8n',
    owner: 'ARC-FRG',
    name: 'AI Agent Spawner',
    trigger: 'Task Input',
    tags: ['agent', 'multi-agent', 'decompose', 'crewai'],
    desc: 'Receive complex task → decompose into sub-tasks → spawn specialized agents in parallel → aggregate outputs → deliver.',
    nodes: [
      _n('n1', 60, 100, 'Task Input', 'ARC-OPT'),
      _n('n2', 240, 100, 'Decompose · Planner', 'ARC-OPT'),
      _n('n3', 440, 30, 'Agent · Research', 'ARC-SCT'),
      _n('n4', 440, 100, 'Agent · Code', 'ARC-FRG'),
      _n('n5', 440, 170, 'Agent · Write', 'CNT-HUB'),
      _n('n6', 660, 100, 'Aggregate Output', 'ARC-OPT'),
      _n('n7', 820, 100, 'Deliver Result', 'ARC-OPT'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n2', 'n4'],
      ['n2', 'n5'],
      ['n3', 'n6'],
      ['n4', 'n6'],
      ['n5', 'n6'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-027',
    category: 'AI/ML',
    source: 'n8n',
    owner: 'ARC-FRG',
    name: 'Prompt A/B Tester',
    trigger: 'New Prompt Version',
    tags: ['prompting', 'A/B', 'optimization', 'evals'],
    desc: 'New prompt variant → run both A and B on test set → score with rubric → statistical significance test → promote winner.',
    nodes: [
      _n('n1', 60, 100, 'New Prompt v2', 'ARC-FRG'),
      _n('n2', 240, 50, 'Run Variant A', 'INF-SC'),
      _n('n3', 240, 150, 'Run Variant B', 'INF-SC'),
      _n('n4', 460, 100, 'Score + Stats Test', 'ARC-OPT'),
      _n('n5', 640, 100, 'Select Winner', 'ARC-FRG'),
      _n('n6', 820, 100, 'Promote + Monitor', 'ARC-FRG'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-028',
    category: 'AI/ML',
    source: 'github',
    owner: 'INF-WS',
    name: 'Data Labeling Pipeline',
    trigger: 'Raw Dataset Upload',
    tags: ['labeling', 'annotation', 'active-learning', 'data'],
    desc: 'Raw data → auto-label easy cases → route hard cases to human → review → export → active learning feedback loop.',
    nodes: [
      _n('n1', 60, 100, 'Raw Dataset', 'INF-WS'),
      _n('n2', 240, 100, 'Auto-Label · Model', 'ARC-FRG'),
      _n('n3', 440, 50, 'High Confidence', 'INF-WS'),
      _n('n4', 440, 150, 'Human Review Queue', 'INF-WS'),
      _n('n5', 660, 100, 'Merge + Export', 'INF-WS'),
      _n('n6', 820, 100, 'Active Learning FB', 'ARC-FRG'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },

  // ── Data & Analytics (6) ────────────────────────────────────────────────
  {
    id: 'TPL-029',
    category: 'DATA',
    source: 'n8n',
    owner: 'INF-WS',
    name: 'ETL Pipeline · Full Stack',
    trigger: 'Schedule · 03:00',
    tags: ['ETL', 'dbt', 'Snowflake', 'data-warehouse'],
    desc: 'Extract from 5 sources → validate schema → transform (dbt) → load to Snowflake → verify row counts → alert on error.',
    nodes: [
      _n('n1', 60, 100, 'Extract · 5 Sources', 'INF-WS'),
      _n('n2', 240, 100, 'Validate Schema', 'INF-FS'),
      _n('n3', 420, 100, 'Transform · dbt', 'INF-FS'),
      _n('n4', 600, 100, 'Load · Snowflake', 'INF-SC'),
      _n('n5', 780, 50, 'Verify Row Counts', 'INF-FS'),
      _n('n6', 780, 150, 'Alert on Error', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-030',
    category: 'DATA',
    source: 'n8n',
    owner: 'INF-SC',
    name: 'Real-time Dashboard Updater',
    trigger: 'Stream · 1s interval',
    tags: ['streaming', 'Kafka', 'dashboard', 'real-time'],
    desc: 'Kafka stream → aggregate 1m window → enrich with meta → push to Grafana/Retool → alert on anomaly.',
    nodes: [
      _n('n1', 60, 100, 'Kafka Stream', 'INF-SC'),
      _n('n2', 240, 100, 'Aggregate · 1m', 'INF-SC'),
      _n('n3', 440, 100, 'Enrich Meta', 'INF-WS'),
      _n('n4', 620, 50, 'Push · Dashboard', 'INF-SC'),
      _n('n5', 620, 150, 'Alert · Anomaly', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5']),
  },
  {
    id: 'TPL-031',
    category: 'DATA',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Anomaly Detection Flow',
    trigger: 'Continuous Stream',
    tags: ['anomaly', 'ML', 'alerting', 'monitoring'],
    desc: 'Time-series stream → statistical window → isolation forest detect → severity score → alert → auto-investigate → ticket.',
    nodes: [
      _n('n1', 60, 100, 'TS Stream', 'INF-SC'),
      _n('n2', 220, 100, 'Stat Window', 'ARC-OPT'),
      _n('n3', 380, 100, 'Isolation Forest', 'ARC-OPT'),
      _n('n4', 540, 100, 'Severity Score', 'ARC-OPT'),
      _n('n5', 700, 50, 'Alert · PagerDuty', 'ARC-OPT'),
      _n('n6', 700, 150, 'Auto Investigate', 'ARC-FRG'),
      _n('n7', 860, 100, 'JIRA Ticket', 'INF-FS'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n3', 'n4'],
      ['n4', 'n5'],
      ['n4', 'n6'],
      ['n5', 'n7'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-032',
    category: 'DATA',
    source: 'github',
    owner: 'ARC-OPT',
    name: 'A/B Test Lifecycle',
    trigger: 'Feature Flag Toggle',
    tags: ['A/B', 'experimentation', 'statsig', 'product'],
    desc: 'Design experiment → deploy flag → monitor traffic split → collect metrics → power + significance test → decide → ship.',
    nodes: [
      _n('n1', 60, 100, 'Design Experiment', 'ARC-OPT'),
      _n('n2', 240, 100, 'Deploy Feature Flag', 'INF-FS'),
      _n('n3', 440, 100, 'Monitor Traffic', 'INF-SC'),
      _n('n4', 620, 100, 'Significance Test', 'ARC-OPT'),
      _n('n5', 800, 50, 'Ship Winner', 'INF-FS'),
      _n('n6', 800, 150, 'Document + Learn', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-033',
    category: 'DATA',
    source: 'n8n',
    owner: 'ARC-SCT',
    name: 'Competitor Monitor',
    trigger: 'Schedule · Daily 06:00',
    tags: ['competitive-intel', 'scraping', 'AI', 'alerts'],
    desc: 'Scrape competitor sites + Crunchbase + LinkedIn → diff vs yesterday → AI summary of changes → alert if significant.',
    nodes: [
      _n('n1', 60, 100, 'Schedule · 06:00', 'ARC-SCT'),
      _n('n2', 240, 50, 'Scrape Sites', 'INF-WS'),
      _n('n3', 240, 150, 'Pull Crunchbase', 'INF-WS'),
      _n('n4', 460, 100, 'Diff vs Yesterday', 'ARC-SCT'),
      _n('n5', 640, 100, 'AI Summary', 'ARC-OPT'),
      _n('n6', 820, 100, 'Alert + Archive', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-034',
    category: 'DATA',
    source: 'n8n',
    owner: 'INF-FS',
    name: 'Data Quality Checker',
    trigger: 'Post-Load Event',
    tags: ['data-quality', 'great-expectations', 'dbt', 'alerts'],
    desc: 'Run Great Expectations suite → flag failed checks → AI explain root cause → route to owner → auto-heal if possible.',
    nodes: [
      _n('n1', 60, 100, 'Post-Load Event', 'INF-FS'),
      _n('n2', 240, 100, 'GE Suite · Run', 'INF-FS'),
      _n('n3', 440, 50, 'All Pass', 'INF-FS'),
      _n('n4', 440, 150, 'Failures Detected', 'INF-FS'),
      _n('n5', 640, 150, 'AI Root Cause', 'ARC-OPT'),
      _n('n6', 800, 150, 'Route + Auto-Heal', 'INF-FS'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },

  // ── Business Ops (6) ────────────────────────────────────────────────────
  {
    id: 'TPL-035',
    category: 'OPS',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Lead Qualification Pipeline',
    trigger: 'Form Submit / Inbound',
    tags: ['CRM', 'lead-scoring', 'sales', 'automation'],
    desc: 'Inbound lead → enrich (Clearbit + LinkedIn) → score (ICP fit + intent) → route to right rep → CRM update → notify.',
    nodes: [
      _n('n1', 60, 100, 'Lead Inbound', 'ARC-OPT'),
      _n('n2', 240, 50, 'Enrich · Clearbit', 'INF-WS'),
      _n('n3', 240, 150, 'Enrich · LinkedIn', 'INF-WS'),
      _n('n4', 460, 100, 'Score · ICP Fit', 'ARC-OPT'),
      _n('n5', 640, 100, 'Route to Rep', 'ARC-OPT'),
      _n('n6', 820, 100, 'CRM + Notify', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-036',
    category: 'OPS',
    source: 'n8n',
    owner: 'LGL-TAX',
    name: 'Invoice Processing Automation',
    trigger: 'Email Attachment',
    tags: ['invoice', 'OCR', 'AP', 'approval'],
    desc: 'Receive invoice email → OCR extract fields → match to PO → route for approval (>$10k = CFO) → trigger payment → archive.',
    nodes: [
      _n('n1', 60, 100, 'Invoice Email', 'LGL-TAX'),
      _n('n2', 240, 100, 'OCR · Extract', 'ARC-FRG'),
      _n('n3', 420, 100, 'Match · PO Number', 'LGL-TAX'),
      _n('n4', 600, 100, 'Approval Route', 'LGL-TAX'),
      _n('n5', 780, 50, 'Trigger Payment', 'LGL-TAX'),
      _n('n6', 780, 150, 'Archive + Audit', 'LGL-TAX'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-037',
    category: 'OPS',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Customer Onboarding Flow',
    trigger: 'Payment Confirmed',
    tags: ['onboarding', 'SaaS', 'email', 'automation'],
    desc: 'Payment confirmed → provision account → welcome sequence (D0/D3/D7) → assign CSM → activate features → NPS at D30.',
    nodes: [
      _n('n1', 60, 100, 'Payment Confirmed', 'ARC-OPT'),
      _n('n2', 240, 100, 'Provision Account', 'INF-FS'),
      _n('n3', 420, 50, 'Welcome D0 Email', 'CNT-NWS'),
      _n('n4', 420, 150, 'Assign CSM', 'ARC-OPT'),
      _n('n5', 640, 100, 'Activate Features', 'INF-FS'),
      _n('n6', 820, 100, 'NPS Survey · D30', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-038',
    category: 'OPS',
    source: 'n8n',
    owner: 'LGL-LAW',
    name: 'Contract Review Pipeline',
    trigger: 'Contract Upload',
    tags: ['contracts', 'legal', 'AI-review', 'e-sign'],
    desc: 'Upload contract → AI extract clauses → flag risky terms → route to counsel → human review → e-sign → archive.',
    nodes: [
      _n('n1', 60, 100, 'Contract Upload', 'LGL-LAW'),
      _n('n2', 240, 100, 'AI · Extract', 'ARC-FRG'),
      _n('n3', 440, 50, 'Flag Risky Terms', 'LGL-LAW'),
      _n('n4', 440, 150, 'Standard Clauses', 'LGL-LAW'),
      _n('n5', 660, 100, 'Counsel Review', 'LGL-LAW'),
      _n('n6', 820, 100, 'E-Sign + Archive', 'LGL-LAW'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-039',
    category: 'OPS',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Support Ticket Triage',
    trigger: 'New Ticket Created',
    tags: ['support', 'triage', 'AI', 'zendesk'],
    desc: 'Ticket in → AI classify (bug/feature/billing/general) → severity score → auto-reply standard cases → assign + SLA track.',
    nodes: [
      _n('n1', 60, 100, 'Ticket Created', 'ARC-OPT'),
      _n('n2', 240, 100, 'AI Classify', 'ARC-FRG'),
      _n('n3', 440, 50, 'Auto-Reply · Low', 'ARC-OPT'),
      _n('n4', 440, 150, 'Assign · High', 'ARC-OPT'),
      _n('n5', 640, 100, 'SLA Timer Start', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5']),
  },
  {
    id: 'TPL-040',
    category: 'OPS',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'Morning Intelligence Brief',
    trigger: 'Daily 05:45',
    tags: ['morning-brief', 'AI', 'digest', 'automation'],
    desc: 'At 05:45: fetch news + market scan + calendar + tasks in parallel → AI compose brief → deliver to Bridge + voice.',
    nodes: [
      _n('n1', 60, 120, 'Trigger · 05:45', 'ARC-OPT'),
      _n('n2', 240, 30, 'News · Top Stories', 'ARC-SCT'),
      _n('n3', 240, 90, 'Market Pre-Open', 'FIN-TRD'),
      _n('n4', 240, 150, 'Calendar · Today', 'ARC-OPT'),
      _n('n5', 240, 210, 'Tasks · Priority', 'ARC-OPT'),
      _n('n6', 500, 120, 'AI · Compose Brief', 'ARC-FRG'),
      _n('n7', 720, 70, 'Deliver · Bridge', 'ARC-OPT'),
      _n('n8', 720, 170, 'Deliver · Voice', 'ARC-OPT'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n1', 'n4'],
      ['n1', 'n5'],
      ['n2', 'n6'],
      ['n3', 'n6'],
      ['n4', 'n6'],
      ['n5', 'n6'],
      ['n6', 'n7'],
      ['n6', 'n8'],
    ),
  },

  // ── GROWTH (8) ──────────────────────────────────────────────────────────────
  {
    id: 'TPL-041',
    category: 'GROWTH',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'Viral Loop Engine',
    trigger: 'User Share Event',
    tags: ['viral', 'loop', 'referral', 'k-factor'],
    desc: 'User shares → track referral source → reward gate → notify invitees → convert → reward sender → calc k-factor.',
    nodes: [
      _n('n1', 60, 100, 'Share Event', 'ARC-OPT'),
      _n('n2', 240, 100, 'Track Referral', 'ARC-OPT'),
      _n('n3', 420, 50, 'Reward Gate', 'ARC-OPT'),
      _n('n4', 420, 150, 'Notify Invitees', 'CNT-HUB'),
      _n('n5', 620, 100, 'Convert + Reward', 'ARC-OPT'),
      _n('n6', 800, 100, 'K-Factor Calc', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-042',
    category: 'GROWTH',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Product-Led Growth Pipeline',
    trigger: 'Trial Signup',
    tags: ['PLG', 'activation', 'aha-moment', 'onboarding'],
    desc: 'Trial signup → track activation milestones → detect aha-moment → trigger upgrade nudge → A/B convert offer → celebrate + retain.',
    nodes: [
      _n('n1', 60, 100, 'Trial Signup', 'ARC-OPT'),
      _n('n2', 240, 100, 'Track Milestones', 'ARC-OPT'),
      _n('n3', 420, 100, 'Aha-Moment Detect', 'ARC-OPT'),
      _n('n4', 600, 50, 'Upgrade Nudge', 'CNT-NWS'),
      _n('n5', 600, 150, 'A/B Offer', 'ARC-OPT'),
      _n('n6', 800, 100, 'Celebrate + Retain', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-043',
    category: 'GROWTH',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Referral Program Automation',
    trigger: 'Referral Link Click',
    tags: ['referral', 'affiliate', 'reward', 'double-sided'],
    desc: 'Referral click → attribute source → sign-up gate → dual reward calc (sender+receiver) → email rewards → track attribution → report.',
    nodes: [
      _n('n1', 60, 100, 'Referral Click', 'CNT-HUB'),
      _n('n2', 240, 100, 'Attribute Source', 'ARC-OPT'),
      _n('n3', 420, 100, 'Sign-Up Gate', 'ARC-OPT'),
      _n('n4', 600, 50, 'Dual Reward Calc', 'ARC-OPT'),
      _n('n5', 600, 150, 'Email Rewards', 'CNT-NWS'),
      _n('n6', 800, 100, 'Attribution Log', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-044',
    category: 'GROWTH',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'User Activation Sprint',
    trigger: 'Day 1 Post-Signup',
    tags: ['activation', 'onboarding', 'D1', 'D3', 'D7'],
    desc: 'D1 → guide to first value event → D3 follow-up if not activated → D7 human touch → inactivate path to cancel save.',
    nodes: [
      _n('n1', 60, 100, 'D1 Trigger', 'ARC-OPT'),
      _n('n2', 240, 100, 'First Value Event?', 'ARC-OPT'),
      _n('n3', 420, 50, 'Activated Path', 'ARC-OPT'),
      _n('n4', 420, 150, 'D3 Nudge Email', 'CNT-NWS'),
      _n('n5', 620, 150, 'D7 Human Touch', 'ARC-OPT'),
      _n('n6', 800, 100, 'Deepen + Expand', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n6'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-045',
    category: 'GROWTH',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Influencer Outreach Pipeline',
    trigger: 'Target List Import',
    tags: ['influencer', 'outreach', 'UGC', 'collaboration'],
    desc: 'Import targets → enrich profile + engagement stats → score fit → personalized outreach → track responses → negotiate → contract → brief.',
    nodes: [
      _n('n1', 60, 100, 'Import Targets', 'CNT-HUB'),
      _n('n2', 240, 100, 'Enrich + Score', 'ARC-SCT'),
      _n('n3', 420, 100, 'Filter High-Fit', 'ARC-OPT'),
      _n('n4', 600, 100, 'Personalized DM', 'CNT-HUB'),
      _n('n5', 780, 50, 'Contract + Brief', 'LGL-LAW'),
      _n('n6', 780, 150, 'Track Response', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-046',
    category: 'GROWTH',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'Churn Prevention Engine',
    trigger: 'Health Score Drop < 60',
    tags: ['churn', 'retention', 'health-score', 'CSM'],
    desc: 'Health score drop → classify risk tier → trigger playbook (email/CSM/incentive) → measure engagement lift → escalate if declining.',
    nodes: [
      _n('n1', 60, 100, 'Health Score Drop', 'ARC-OPT'),
      _n('n2', 240, 100, 'Risk Classification', 'ARC-OPT'),
      _n('n3', 420, 50, 'Email Playbook', 'CNT-NWS'),
      _n('n4', 420, 150, 'CSM Task', 'ARC-OPT'),
      _n('n5', 620, 100, 'Measure Lift', 'ARC-OPT'),
      _n('n6', 800, 100, 'Escalate / Close', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-047',
    category: 'GROWTH',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Growth Experiment Tracker',
    trigger: 'New Experiment Launch',
    tags: ['experimentation', 'ICE', 'growth', 'hypothesis'],
    desc: 'New hypothesis → ICE score → approve gate → run experiment → collect results → stat significance → ship or kill → document.',
    nodes: [
      _n('n1', 60, 100, 'Hypothesis', 'ARC-OPT'),
      _n('n2', 240, 100, 'ICE Score', 'ARC-OPT'),
      _n('n3', 420, 100, 'Approve Gate', 'ARC-OPT'),
      _n('n4', 600, 100, 'Run Experiment', 'INF-FS'),
      _n('n5', 780, 50, 'Stat Test', 'ARC-OPT'),
      _n('n6', 780, 150, 'Ship / Kill', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-048',
    category: 'GROWTH',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Revenue Expansion Automation',
    trigger: 'Usage Threshold Hit',
    tags: ['upsell', 'expansion', 'MRR', 'PQL'],
    desc: 'Usage spike → qualify PQL → run expansion playbook → CSM trigger → upsell offer → contract amendment → log MRR expansion.',
    nodes: [
      _n('n1', 60, 100, 'Usage Spike', 'ARC-OPT'),
      _n('n2', 240, 100, 'PQL Qualify', 'ARC-OPT'),
      _n('n3', 420, 100, 'Expansion Playbook', 'ARC-OPT'),
      _n('n4', 600, 50, 'CSM + Offer', 'ARC-OPT'),
      _n('n5', 600, 150, 'Contract Amend', 'LGL-LAW'),
      _n('n6', 800, 100, 'Log MRR Delta', 'FIN-TRD'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },

  // ── SALES (8) ──────────────────────────────────────────────────────────────
  {
    id: 'TPL-049',
    category: 'SALES',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Cold Outreach Sequencer',
    trigger: 'Prospect List Upload',
    tags: ['cold-email', 'sequences', 'reply', 'personalization'],
    desc: 'Upload prospects → enrich (LinkedIn + Clearbit) → AI personalize → D1 email → D3 follow-up → D7 breakup → reply auto-detect → book.',
    nodes: [
      _n('n1', 60, 100, 'Prospect Upload', 'ARC-OPT'),
      _n('n2', 240, 100, 'Enrich + Personalize', 'INF-WS'),
      _n('n3', 420, 100, 'D1 Email · AI', 'CNT-NWS'),
      _n('n4', 600, 50, 'D3 Follow-Up', 'CNT-NWS'),
      _n('n5', 600, 150, 'Reply Detected?', 'ARC-OPT'),
      _n('n6', 800, 100, 'Book · Calendly', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-050',
    category: 'SALES',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Deal Stage Automation',
    trigger: 'CRM Stage Change',
    tags: ['CRM', 'deal-flow', 'Salesforce', 'automation'],
    desc: 'Stage change → update CRM → trigger stage-specific tasks → notify stakeholders → update forecast → set next follow-up.',
    nodes: [
      _n('n1', 60, 100, 'Stage Change', 'ARC-OPT'),
      _n('n2', 240, 100, 'Update CRM', 'ARC-OPT'),
      _n('n3', 420, 50, 'Stage Tasks', 'ARC-OPT'),
      _n('n4', 420, 150, 'Notify Team', 'ARC-OPT'),
      _n('n5', 620, 100, 'Update Forecast', 'FIN-TRD'),
      _n('n6', 800, 100, 'Set Follow-Up', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-051',
    category: 'SALES',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'AI Proposal Generator',
    trigger: 'Deal Qualified Stage',
    tags: ['proposal', 'AI-writing', 'personalization', 'pitch'],
    desc: 'Deal qualifies → pull CRM context + discovery notes → AI draft proposal → pricing calc → design PDF → approval gate → send + track.',
    nodes: [
      _n('n1', 60, 100, 'Deal Qualified', 'ARC-OPT'),
      _n('n2', 240, 100, 'Pull CRM Context', 'ARC-OPT'),
      _n('n3', 420, 100, 'AI Draft Proposal', 'ARC-FRG'),
      _n('n4', 600, 50, 'Pricing Calc', 'FIN-TRD'),
      _n('n5', 600, 150, 'Design + PDF', 'CNT-HUB'),
      _n('n6', 800, 100, 'Send + Track', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-052',
    category: 'SALES',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'Pipeline Health Monitor',
    trigger: 'Daily 07:00',
    tags: ['pipeline', 'health', 'forecast', 'coaching'],
    desc: 'Daily scan → calc pipeline coverage + velocity + age by stage → flag stale deals → coach suggestions → alert rep + manager.',
    nodes: [
      _n('n1', 60, 100, 'Daily 07:00', 'ARC-OPT'),
      _n('n2', 240, 100, 'Pipeline Scan', 'ARC-OPT'),
      _n('n3', 420, 100, 'Coverage + Velocity', 'ARC-OPT'),
      _n('n4', 600, 50, 'Flag Stale Deals', 'ARC-OPT'),
      _n('n5', 600, 150, 'AI Coach Tips', 'ARC-FRG'),
      _n('n6', 800, 100, 'Alert + Report', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-053',
    category: 'SALES',
    source: 'jarvis',
    owner: 'FIN-TRD',
    name: 'Sales Forecasting Engine',
    trigger: 'Weekly · Monday',
    tags: ['forecasting', 'AI', 'ML', 'accuracy'],
    desc: 'Pull pipeline snapshot → apply ML win probability → scenario model (base/best/worst) → compare vs quota → AI narrative → board report.',
    nodes: [
      _n('n1', 60, 100, 'Pipeline Snap', 'ARC-OPT'),
      _n('n2', 240, 100, 'ML Win Prob', 'ARC-FRG'),
      _n('n3', 420, 100, 'Scenario Model', 'FIN-TRD'),
      _n('n4', 620, 50, 'vs Quota Delta', 'FIN-TRD'),
      _n('n5', 620, 150, 'AI Narrative', 'ARC-OPT'),
      _n('n6', 800, 100, 'Board Report', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-054',
    category: 'SALES',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Win/Loss Analysis Pipeline',
    trigger: 'Deal Closed (Won/Lost)',
    tags: ['win-loss', 'insights', 'competitive', 'coaching'],
    desc: 'Deal closes → auto-send exit survey → scrape battlecard signals → AI analyze patterns → update competitive intel → coaching report.',
    nodes: [
      _n('n1', 60, 100, 'Deal Closed', 'ARC-OPT'),
      _n('n2', 240, 50, 'Exit Survey', 'ARC-OPT'),
      _n('n3', 240, 150, 'Battlecard Signal', 'ARC-SCT'),
      _n('n4', 450, 100, 'Pattern Analysis', 'ARC-FRG'),
      _n('n5', 650, 100, 'Competitive Intel', 'ARC-SCT'),
      _n('n6', 820, 100, 'Coaching Report', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-055',
    category: 'SALES',
    source: 'n8n',
    owner: 'LGL-LAW',
    name: 'Contract-to-Close Automation',
    trigger: 'Verbal Agreement',
    tags: ['contract', 'e-sign', 'redlines', 'legal'],
    desc: 'Verbal yes → generate MSA from template → legal review gate → redline AI check → e-sign → CRM close → invoice trigger → kickoff.',
    nodes: [
      _n('n1', 60, 100, 'Verbal Yes', 'ARC-OPT'),
      _n('n2', 240, 100, 'Generate MSA', 'LGL-LAW'),
      _n('n3', 420, 100, 'AI Redline Check', 'ARC-FRG'),
      _n('n4', 600, 100, 'E-Sign · Docusign', 'LGL-LAW'),
      _n('n5', 780, 50, 'CRM Close + Invoice', 'FIN-TRD'),
      _n('n6', 780, 150, 'Kickoff Trigger', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-056',
    category: 'SALES',
    source: 'n8n',
    owner: 'ARC-SCT',
    name: 'Account-Based Marketing Stack',
    trigger: 'Target Account Added',
    tags: ['ABM', 'intent-data', 'personalization', 'B2B'],
    desc: 'Account added → intent data pull → buying committee map → personalized content per persona → multi-channel sequence → engagement score → alert SDR.',
    nodes: [
      _n('n1', 60, 100, 'Account Added', 'ARC-SCT'),
      _n('n2', 240, 100, 'Intent Data Pull', 'INF-WS'),
      _n('n3', 420, 100, 'Committee Map', 'ARC-SCT'),
      _n('n4', 600, 50, 'Personalize Content', 'ARC-FRG'),
      _n('n5', 600, 150, 'Multi-Channel Seq', 'CNT-HUB'),
      _n('n6', 800, 100, 'Alert SDR', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },

  // ── RESEARCH (6) ──────────────────────────────────────────────────────────
  {
    id: 'TPL-057',
    category: 'RESEARCH',
    source: 'jarvis',
    owner: 'ARC-SCT',
    name: 'Deep Research Orchestrator',
    trigger: 'Research Query Input',
    tags: ['deep-research', 'multi-source', 'synthesis', 'report'],
    desc: 'Query → decompose into sub-questions → parallel: web scrape + academic + news + X → aggregate → dedup → AI synthesize → structured report.',
    nodes: [
      _n('n1', 60, 100, 'Query Input', 'ARC-SCT'),
      _n('n2', 240, 100, 'Decompose Qs', 'ARC-OPT'),
      _n('n3', 420, 30, 'Web Scrape', 'INF-WS'),
      _n('n4', 420, 90, 'Academic DB', 'INF-WS'),
      _n('n5', 420, 150, 'News + X Feed', 'ARC-SCT'),
      _n('n6', 620, 100, 'Aggregate + Dedup', 'ARC-FRG'),
      _n('n7', 800, 100, 'Structured Report', 'ARC-FRG'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n2', 'n4'],
      ['n2', 'n5'],
      ['n3', 'n6'],
      ['n4', 'n6'],
      ['n5', 'n6'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-058',
    category: 'RESEARCH',
    source: 'n8n',
    owner: 'ARC-SCT',
    name: 'Market Sizing Pipeline',
    trigger: 'New Market Definition',
    tags: ['TAM', 'SAM', 'SOM', 'market-research'],
    desc: 'Define market → pull industry reports + census data + competitor revenue → AI bottom-up calc → TAM/SAM/SOM model → confidence score → slide deck.',
    nodes: [
      _n('n1', 60, 100, 'Market Defined', 'ARC-SCT'),
      _n('n2', 240, 50, 'Industry Reports', 'INF-WS'),
      _n('n3', 240, 150, 'Competitor Revenue', 'ARC-SCT'),
      _n('n4', 440, 100, 'Bottom-Up Calc', 'ARC-FRG'),
      _n('n5', 640, 100, 'TAM/SAM/SOM', 'FIN-TRD'),
      _n('n6', 820, 100, 'Slide Deck Output', 'CNT-HUB'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-059',
    category: 'RESEARCH',
    source: 'jarvis',
    owner: 'ARC-SCT',
    name: 'Trend Prediction Engine',
    trigger: 'Weekly Data Refresh',
    tags: ['trends', 'prediction', 'early-signal', 'AI'],
    desc: 'Refresh data → scan social signals + patent filings + job postings + funding rounds → ML trend scoring → early signal detection → brief + alert.',
    nodes: [
      _n('n1', 60, 100, 'Data Refresh', 'ARC-SCT'),
      _n('n2', 240, 30, 'Social Signals', 'CNT-X'),
      _n('n3', 240, 90, 'Patent Filings', 'INF-WS'),
      _n('n4', 240, 150, 'Job Postings', 'INF-WS'),
      _n('n5', 240, 210, 'Funding Rounds', 'FIN-TRD'),
      _n('n6', 480, 120, 'ML Score + Rank', 'ARC-FRG'),
      _n('n7', 680, 120, 'Early Signal Brief', 'ARC-SCT'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n1', 'n4'],
      ['n1', 'n5'],
      ['n2', 'n6'],
      ['n3', 'n6'],
      ['n4', 'n6'],
      ['n5', 'n6'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-060',
    category: 'RESEARCH',
    source: 'n8n',
    owner: 'ARC-SCT',
    name: 'Academic Research Synthesizer',
    trigger: 'New Paper Batch',
    tags: ['arxiv', 'papers', 'literature', 'synthesis'],
    desc: 'New papers → parse abstracts → relevance filter → full-text extract key findings → cluster by theme → AI meta-analysis → weekly digest.',
    nodes: [
      _n('n1', 60, 100, 'Paper Batch', 'INF-WS'),
      _n('n2', 240, 100, 'Relevance Filter', 'ARC-FRG'),
      _n('n3', 420, 100, 'Extract Findings', 'ARC-FRG'),
      _n('n4', 600, 100, 'Theme Cluster', 'ARC-FRG'),
      _n('n5', 780, 100, 'Meta-Analysis + Digest', 'ARC-SCT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5']),
  },
  {
    id: 'TPL-061',
    category: 'RESEARCH',
    source: 'github',
    owner: 'ARC-SCT',
    name: 'Patent Landscape Analyzer',
    trigger: 'Technology Keyword Set',
    tags: ['patents', 'IP', 'freedom-to-operate', 'landscape'],
    desc: 'Keywords → USPTO + EPO + Google Patents API → parse claims → cluster by IPC class → whitespace map → AI FTO summary → legal report.',
    nodes: [
      _n('n1', 60, 100, 'Keywords Input', 'ARC-SCT'),
      _n('n2', 240, 50, 'USPTO + EPO Pull', 'INF-WS'),
      _n('n3', 240, 150, 'Google Patents', 'INF-WS'),
      _n('n4', 460, 100, 'Parse + Cluster', 'ARC-FRG'),
      _n('n5', 660, 100, 'Whitespace Map', 'ARC-SCT'),
      _n('n6', 820, 100, 'FTO Report', 'LGL-LAW'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-062',
    category: 'RESEARCH',
    source: 'jarvis',
    owner: 'ARC-SCT',
    name: 'Competitive Intelligence Hub',
    trigger: 'Continuous · 4h cycle',
    tags: ['competitive', 'CI', 'positioning', 'SWOT'],
    desc: 'Every 4h: scrape 10 competitor sites + G2 + Crunchbase + job boards → detect pricing/product/hiring changes → SWOT delta → alert if significant.',
    nodes: [
      _n('n1', 60, 100, '4h Trigger', 'ARC-SCT'),
      _n('n2', 240, 50, 'Scrape Sites + G2', 'INF-WS'),
      _n('n3', 240, 150, 'Crunchbase + Jobs', 'INF-WS'),
      _n('n4', 460, 100, 'Change Detection', 'ARC-SCT'),
      _n('n5', 660, 100, 'SWOT Delta', 'ARC-FRG'),
      _n('n6', 820, 100, 'Alert If Material', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },

  // ── WEB3 (6) ──────────────────────────────────────────────────────────────
  {
    id: 'TPL-063',
    category: 'WEB3',
    source: 'jarvis',
    owner: 'FIN-BOT',
    name: 'On-Chain Event Monitor',
    trigger: 'Webhook · Smart Contract Event',
    tags: ['on-chain', 'events', 'DeFi', 'alerts'],
    desc: 'Contract event fires → decode calldata → classify event type → enrich with price/gas data → alert if whale (>$1M) → log + dashboard.',
    nodes: [
      _n('n1', 60, 100, 'Contract Event', 'FIN-BOT'),
      _n('n2', 240, 100, 'Decode Calldata', 'FIN-BOT'),
      _n('n3', 420, 100, 'Classify Type', 'ARC-OPT'),
      _n('n4', 600, 50, 'Enrich Price+Gas', 'FIN-TRD'),
      _n('n5', 600, 150, 'Whale Gate >$1M', 'FIN-TRD'),
      _n('n6', 800, 100, 'Alert + Log', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-064',
    category: 'WEB3',
    source: 'jarvis',
    owner: 'FIN-BOT',
    name: 'DeFi Yield Optimizer',
    trigger: 'Hourly Rate Scan',
    tags: ['DeFi', 'yield', 'APY', 'rebalance', 'Aave', 'Compound'],
    desc: 'Hourly scan Aave + Compound + Curve + Pendle → rank by risk-adjusted yield → gas cost calc → execute rebalance if delta > 0.5% → notify.',
    nodes: [
      _n('n1', 60, 100, 'Hourly Scan', 'FIN-BOT'),
      _n('n2', 240, 50, 'Aave + Compound', 'FIN-BOT'),
      _n('n3', 240, 150, 'Curve + Pendle', 'FIN-BOT'),
      _n('n4', 460, 100, 'Rank Risk-Adj', 'FIN-TRD'),
      _n('n5', 640, 100, 'Gas + Delta Check', 'FIN-BOT'),
      _n('n6', 820, 100, 'Execute Rebalance', 'FIN-BOT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-065',
    category: 'WEB3',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'NFT Collection Launch',
    trigger: 'Launch Date T-7',
    tags: ['NFT', 'launch', 'mint', 'community', 'allowlist'],
    desc: 'T-7: build allowlist → T-3: teaser content burst → T-1: final hype → Mint Day: monitor + alert → post-mint analytics → holder rewards.',
    nodes: [
      _n('n1', 60, 100, 'T-7 Launch Prep', 'CNT-HUB'),
      _n('n2', 240, 50, 'Allowlist Build', 'FIN-BOT'),
      _n('n3', 240, 150, 'Content Teaser Burst', 'CNT-HUB'),
      _n('n4', 460, 100, 'T-1 Final Hype', 'CNT-HUB'),
      _n('n5', 640, 100, 'Mint Day Monitor', 'FIN-BOT'),
      _n('n6', 820, 100, 'Analytics + Rewards', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-066',
    category: 'WEB3',
    source: 'github',
    owner: 'FIN-BOT',
    name: 'Token Distribution Pipeline',
    trigger: 'Distribution Event',
    tags: ['airdrop', 'vesting', 'token', 'smart-contract'],
    desc: 'Snapshot wallets → eligibility filter → merkle tree construct → deploy distributor contract → claim portal → vesting schedule → monitor claims.',
    nodes: [
      _n('n1', 60, 100, 'Wallet Snapshot', 'FIN-BOT'),
      _n('n2', 240, 100, 'Eligibility Filter', 'FIN-BOT'),
      _n('n3', 420, 100, 'Merkle Tree Build', 'INF-FS'),
      _n('n4', 600, 100, 'Deploy Contract', 'INF-FS'),
      _n('n5', 780, 50, 'Claim Portal Live', 'INF-WEB'),
      _n('n6', 780, 150, 'Monitor Claims', 'FIN-BOT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-067',
    category: 'WEB3',
    source: 'github',
    owner: 'FIN-BOT',
    name: 'DAO Governance Processor',
    trigger: 'Proposal Created',
    tags: ['DAO', 'governance', 'voting', 'quorum'],
    desc: 'Proposal created → AI summarize → notify holders → voting period open → tally votes → quorum check → execute if passed → on-chain log.',
    nodes: [
      _n('n1', 60, 100, 'Proposal Created', 'FIN-BOT'),
      _n('n2', 240, 100, 'AI Summarize', 'ARC-FRG'),
      _n('n3', 420, 100, 'Notify Holders', 'CNT-HUB'),
      _n('n4', 600, 100, 'Tally + Quorum', 'FIN-BOT'),
      _n('n5', 780, 50, 'Execute If Passed', 'FIN-BOT'),
      _n('n6', 780, 150, 'On-Chain Log', 'FIN-BOT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-068',
    category: 'WEB3',
    source: 'jarvis',
    owner: 'FIN-TRD',
    name: 'Wallet Risk Analyzer',
    trigger: 'Large Transaction Alert',
    tags: ['wallet', 'risk', 'AML', 'on-chain-analytics'],
    desc: 'Large tx detected → trace wallet history → check sanctions lists → calc risk score → graph known bad actors → alert compliance → file SAR if needed.',
    nodes: [
      _n('n1', 60, 100, 'Large Tx Alert', 'FIN-TRD'),
      _n('n2', 240, 100, 'Trace History', 'FIN-BOT'),
      _n('n3', 420, 50, 'Sanctions Check', 'LGL-TAX'),
      _n('n4', 420, 150, 'Bad Actor Graph', 'FIN-TRD'),
      _n('n5', 640, 100, 'Risk Score', 'FIN-TRD'),
      _n('n6', 820, 100, 'Alert + SAR Gate', 'LGL-LAW'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },

  // ── SECURITY (6) ──────────────────────────────────────────────────────────
  {
    id: 'TPL-069',
    category: 'SECURITY',
    source: 'n8n',
    owner: 'INF-HCK',
    name: 'Threat Hunt Pipeline',
    trigger: 'IOC Feed Update',
    tags: ['threat-hunting', 'IOC', 'MITRE', 'ATT&CK'],
    desc: 'New IOC feed → normalize indicators → correlate with SIEM logs → ATT&CK TTP mapping → hunt query gen → analyst queue → containment.',
    nodes: [
      _n('n1', 60, 100, 'IOC Feed', 'INF-HCK'),
      _n('n2', 240, 100, 'Normalize IOCs', 'INF-HCK'),
      _n('n3', 420, 50, 'SIEM Correlate', 'INF-HCK'),
      _n('n4', 420, 150, 'ATT&CK Map', 'INF-HCK'),
      _n('n5', 640, 100, 'Hunt Query Gen', 'ARC-FRG'),
      _n('n6', 820, 100, 'Analyst Queue', 'INF-HCK'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-070',
    category: 'SECURITY',
    source: 'github',
    owner: 'INF-HCK',
    name: 'Incident Response Orchestrator',
    trigger: 'Severity 1 Alert',
    tags: ['IR', 'SOAR', 'containment', 'forensics'],
    desc: 'Sev-1 alert → assemble IR team → isolate host → collect forensics → parallel threat intel + timeline build → eradicate → recover → post-mortem.',
    nodes: [
      _n('n1', 60, 100, 'Sev-1 Alert', 'INF-HCK'),
      _n('n2', 240, 50, 'Assemble IR Team', 'INF-HCK'),
      _n('n3', 240, 150, 'Isolate Host', 'INF-HCK'),
      _n('n4', 460, 100, 'Collect Forensics', 'INF-HCK'),
      _n('n5', 640, 50, 'Threat Intel', 'ARC-SCT'),
      _n('n6', 640, 150, 'Timeline Build', 'INF-HCK'),
      _n('n7', 820, 100, 'Eradicate + Recover', 'INF-HCK'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n2', 'n4'],
      ['n3', 'n4'],
      ['n4', 'n5'],
      ['n4', 'n6'],
      ['n5', 'n7'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-071',
    category: 'SECURITY',
    source: 'n8n',
    owner: 'INF-HCK',
    name: 'Compliance Audit Automation',
    trigger: 'Quarterly Audit Trigger',
    tags: ['compliance', 'SOC2', 'ISO27001', 'evidence'],
    desc: 'Audit trigger → collect evidence from 12 control families → auto-map to framework → gap analysis → AI remediation plan → auditor package.',
    nodes: [
      _n('n1', 60, 100, 'Audit Trigger', 'INF-HCK'),
      _n('n2', 240, 100, 'Collect Evidence', 'INF-HCK'),
      _n('n3', 420, 100, 'Framework Map', 'INF-HCK'),
      _n('n4', 600, 100, 'Gap Analysis', 'ARC-FRG'),
      _n('n5', 780, 50, 'Remediation Plan', 'INF-HCK'),
      _n('n6', 780, 150, 'Auditor Package', 'LGL-LAW'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-072',
    category: 'SECURITY',
    source: 'jarvis',
    owner: 'INF-HCK',
    name: 'SIEM Alert Correlator',
    trigger: 'Continuous Alert Stream',
    tags: ['SIEM', 'correlation', 'noise-reduction', 'triage'],
    desc: 'Raw alerts stream → dedup + normalize → ML noise filter → correlate into incidents → priority score → route to analyst or auto-close.',
    nodes: [
      _n('n1', 60, 100, 'Alert Stream', 'INF-HCK'),
      _n('n2', 240, 100, 'Dedup + Normalize', 'INF-HCK'),
      _n('n3', 420, 100, 'ML Noise Filter', 'ARC-FRG'),
      _n('n4', 600, 100, 'Correlate Incidents', 'INF-HCK'),
      _n('n5', 780, 50, 'Route Analyst', 'INF-HCK'),
      _n('n6', 780, 150, 'Auto-Close Low', 'INF-HCK'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-073',
    category: 'SECURITY',
    source: 'github',
    owner: 'INF-HCK',
    name: 'Pen Test Report Generator',
    trigger: 'Engagement Complete',
    tags: ['pentest', 'report', 'CVSS', 'remediation'],
    desc: 'Engagement done → parse tool outputs (Burp+Nessus+Metasploit) → CVSS score → prioritize findings → AI narrative → exec summary → PDF.',
    nodes: [
      _n('n1', 60, 100, 'Engagement Done', 'INF-HCK'),
      _n('n2', 240, 50, 'Parse Burp+Nessus', 'INF-HCK'),
      _n('n3', 240, 150, 'Parse Metasploit', 'INF-HCK'),
      _n('n4', 460, 100, 'CVSS Score + Priority', 'INF-HCK'),
      _n('n5', 660, 100, 'AI Narrative', 'ARC-FRG'),
      _n('n6', 820, 100, 'PDF Report', 'CNT-HUB'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-074',
    category: 'SECURITY',
    source: 'jarvis',
    owner: 'INF-HCK',
    name: 'Zero-Day Response Protocol',
    trigger: 'CVE Published · CVSS ≥ 9',
    tags: ['zero-day', 'CVE', 'patch', 'emergency'],
    desc: 'CVE ≥ 9 published → asset inventory scan → blast radius calc → emergency war room → patch pipeline → verification scan → close.',
    nodes: [
      _n('n1', 60, 100, 'CVE Alert ≥9', 'INF-HCK'),
      _n('n2', 240, 100, 'Asset Inventory Scan', 'INF-SC'),
      _n('n3', 420, 100, 'Blast Radius Calc', 'INF-HCK'),
      _n('n4', 600, 50, 'Emergency War Room', 'INF-HCK'),
      _n('n5', 600, 150, 'Patch Pipeline', 'INF-FS'),
      _n('n6', 800, 100, 'Verify + Close', 'INF-HCK'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },

  // ── INFRA (6) ──────────────────────────────────────────────────────────────
  {
    id: 'TPL-075',
    category: 'INFRA',
    source: 'github',
    owner: 'INF-FS',
    name: 'Chaos Engineering Pipeline',
    trigger: 'Weekly Chaos Day',
    tags: ['chaos', 'resilience', 'fault-injection', 'SRE'],
    desc: 'Schedule chaos day → select blast radius (low) → inject fault scenarios → monitor steady-state → auto-rollback if SLO breached → report.',
    nodes: [
      _n('n1', 60, 100, 'Chaos Day Trigger', 'INF-FS'),
      _n('n2', 240, 100, 'Select Blast Radius', 'INF-FS'),
      _n('n3', 420, 100, 'Inject Fault', 'INF-FS'),
      _n('n4', 600, 50, 'Monitor SLOs', 'INF-SC'),
      _n('n5', 600, 150, 'Rollback If Breach', 'INF-WEB'),
      _n('n6', 800, 100, 'Resilience Report', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-076',
    category: 'INFRA',
    source: 'n8n',
    owner: 'INF-SC',
    name: 'Capacity Planning Automation',
    trigger: 'Monthly Forecast Run',
    tags: ['capacity', 'scaling', 'cost', 'forecast'],
    desc: 'Monthly run → pull 90d usage trends → ML growth model → scenario planning (p50/p90/p99) → cost projection → provisioning plan → approval.',
    nodes: [
      _n('n1', 60, 100, 'Monthly Forecast', 'INF-SC'),
      _n('n2', 240, 100, '90d Usage Trends', 'INF-SC'),
      _n('n3', 420, 100, 'ML Growth Model', 'ARC-FRG'),
      _n('n4', 600, 100, 'Scenario Planning', 'INF-SC'),
      _n('n5', 780, 50, 'Cost Projection', 'FIN-TRD'),
      _n('n6', 780, 150, 'Provision Plan', 'INF-SC'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-077',
    category: 'INFRA',
    source: 'n8n',
    owner: 'INF-FS',
    name: 'Runbook Automation Engine',
    trigger: 'Alert Fires',
    tags: ['runbook', 'SRE', 'auto-remediation', 'ops'],
    desc: 'Alert fires → look up runbook → classify issue type → execute automated steps → check resolution → escalate if unresolved → document actions.',
    nodes: [
      _n('n1', 60, 100, 'Alert Fires', 'INF-FS'),
      _n('n2', 240, 100, 'Lookup Runbook', 'INF-FS'),
      _n('n3', 420, 100, 'Classify Issue', 'ARC-FRG'),
      _n('n4', 600, 100, 'Execute Steps', 'INF-FS'),
      _n('n5', 780, 50, 'Resolved?', 'INF-FS'),
      _n('n6', 780, 150, 'Escalate + Doc', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-078',
    category: 'INFRA',
    source: 'jarvis',
    owner: 'INF-SC',
    name: 'Observability Pipeline',
    trigger: 'Continuous Telemetry',
    tags: ['observability', 'OTEL', 'traces', 'metrics', 'logs'],
    desc: 'Telemetry stream → OTel collect → enrich with service context → ML anomaly baseline → alert on deviation → auto-trace sampling boost.',
    nodes: [
      _n('n1', 60, 100, 'OTel Stream', 'INF-SC'),
      _n('n2', 240, 100, 'Collect + Enrich', 'INF-SC'),
      _n('n3', 420, 100, 'ML Baseline', 'ARC-FRG'),
      _n('n4', 600, 50, 'Anomaly Alert', 'ARC-OPT'),
      _n('n5', 600, 150, 'Trace Sample Boost', 'INF-SC'),
      _n('n6', 800, 100, 'Dashboard Update', 'INF-SC'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-079',
    category: 'INFRA',
    source: 'n8n',
    owner: 'INF-SC',
    name: 'Cloud Cost Optimizer',
    trigger: 'Daily Cost Report',
    tags: ['FinOps', 'cloud-cost', 'rightsizing', 'waste'],
    desc: 'Daily cost pull → identify waste (idle resources, oversized) → rightsizing recommendations → auto-apply approved rules → track savings → report.',
    nodes: [
      _n('n1', 60, 100, 'Daily Cost Pull', 'INF-SC'),
      _n('n2', 240, 100, 'Identify Waste', 'ARC-FRG'),
      _n('n3', 420, 100, 'Rightsize Recs', 'INF-SC'),
      _n('n4', 600, 50, 'Auto-Apply Rules', 'INF-SC'),
      _n('n5', 600, 150, 'Track Savings', 'FIN-TRD'),
      _n('n6', 800, 100, 'FinOps Report', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-080',
    category: 'INFRA',
    source: 'github',
    owner: 'INF-FS',
    name: 'Disaster Recovery Drill',
    trigger: 'Quarterly DR Test',
    tags: ['DR', 'RTO', 'RPO', 'failover', 'backup'],
    desc: 'Trigger DR drill → snapshot all critical systems → simulate failure → initiate failover → validate RTO/RPO → measure gaps → update runbooks.',
    nodes: [
      _n('n1', 60, 100, 'DR Drill Trigger', 'INF-FS'),
      _n('n2', 240, 100, 'Snapshot Critical', 'INF-SC'),
      _n('n3', 420, 100, 'Simulate Failure', 'INF-FS'),
      _n('n4', 600, 100, 'Initiate Failover', 'INF-WEB'),
      _n('n5', 780, 50, 'Validate RTO/RPO', 'INF-FS'),
      _n('n6', 780, 150, 'Update Runbooks', 'INF-FS'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },

  // ── PRODUCT (6) ──────────────────────────────────────────────────────────
  {
    id: 'TPL-081',
    category: 'PRODUCT',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Feature Launch Checklist',
    trigger: 'Feature Flag: Launch Date',
    tags: ['launch', 'checklist', 'GTM', 'coordination'],
    desc: 'Launch date set → trigger eng + design + marketing + legal checklists in parallel → gate on all green → staged rollout → monitor → celebrate.',
    nodes: [
      _n('n1', 60, 100, 'Launch Date Set', 'ARC-OPT'),
      _n('n2', 240, 30, 'Eng Checklist', 'INF-FS'),
      _n('n3', 240, 90, 'Design QA', 'INF-WEB'),
      _n('n4', 240, 150, 'Marketing Brief', 'CNT-HUB'),
      _n('n5', 240, 210, 'Legal Clear', 'LGL-LAW'),
      _n('n6', 500, 120, 'All Green Gate', 'ARC-OPT'),
      _n('n7', 700, 120, 'Staged Rollout', 'INF-FS'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n1', 'n4'],
      ['n1', 'n5'],
      ['n2', 'n6'],
      ['n3', 'n6'],
      ['n4', 'n6'],
      ['n5', 'n6'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-082',
    category: 'PRODUCT',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'User Journey Intelligence',
    trigger: 'Segment Event Stream',
    tags: ['user-journey', 'analytics', 'drop-off', 'funnel'],
    desc: 'Event stream → reconstruct user sessions → funnel visualization → identify drop-off points → AI hypothesis gen → prioritize fixes → A/B test.',
    nodes: [
      _n('n1', 60, 100, 'Event Stream', 'ARC-OPT'),
      _n('n2', 240, 100, 'Session Reconstruct', 'ARC-FRG'),
      _n('n3', 420, 100, 'Funnel Analysis', 'ARC-OPT'),
      _n('n4', 600, 100, 'Drop-Off Identify', 'ARC-OPT'),
      _n('n5', 780, 50, 'AI Hypotheses', 'ARC-FRG'),
      _n('n6', 780, 150, 'A/B Test Queue', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-083',
    category: 'PRODUCT',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Roadmap Sync Automation',
    trigger: 'Quarterly Planning',
    tags: ['roadmap', 'JIRA', 'OKR', 'alignment', 'product'],
    desc: 'Planning kick → pull OKRs + customer requests + tech debt → AI prioritization matrix → roadmap draft → stakeholder review → JIRA sync.',
    nodes: [
      _n('n1', 60, 100, 'Planning Kick', 'ARC-OPT'),
      _n('n2', 240, 50, 'Pull OKRs + CRs', 'ARC-OPT'),
      _n('n3', 240, 150, 'Tech Debt Assess', 'INF-FS'),
      _n('n4', 460, 100, 'AI Priority Matrix', 'ARC-FRG'),
      _n('n5', 660, 100, 'Roadmap Draft', 'ARC-OPT'),
      _n('n6', 820, 100, 'Stakeholder → JIRA', 'INF-FS'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-084',
    category: 'PRODUCT',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'NPS Action Pipeline',
    trigger: 'NPS Survey Response',
    tags: ['NPS', 'CSAT', 'action', 'close-loop'],
    desc: 'NPS response → segment (Promoter/Passive/Detractor) → Promoter: case study ask + referral → Detractor: CSM + root cause → close loop email.',
    nodes: [
      _n('n1', 60, 100, 'NPS Response', 'ARC-OPT'),
      _n('n2', 240, 100, 'Score Segment', 'ARC-OPT'),
      _n('n3', 420, 50, 'Promoter Path', 'ARC-OPT'),
      _n('n4', 420, 150, 'Detractor Path', 'ARC-OPT'),
      _n('n5', 640, 50, 'Case Study + Ref', 'CNT-HUB'),
      _n('n6', 640, 150, 'CSM + Root Cause', 'ARC-OPT'),
      _n('n7', 820, 100, 'Close Loop Email', 'CNT-NWS'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n2', 'n4'],
      ['n3', 'n5'],
      ['n4', 'n6'],
      ['n5', 'n7'],
      ['n6', 'n7'],
    ),
  },
  {
    id: 'TPL-085',
    category: 'PRODUCT',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Beta Feedback Loop',
    trigger: 'Beta User Event',
    tags: ['beta', 'feedback', 'iteration', 'product-discovery'],
    desc: 'Beta activity → in-app survey trigger → collect feedback → cluster themes with AI → update backlog → notify beta users of fixes → re-survey.',
    nodes: [
      _n('n1', 60, 100, 'Beta Activity', 'ARC-OPT'),
      _n('n2', 240, 100, 'In-App Survey', 'ARC-OPT'),
      _n('n3', 420, 100, 'AI Cluster Themes', 'ARC-FRG'),
      _n('n4', 600, 100, 'Update Backlog', 'INF-FS'),
      _n('n5', 780, 50, 'Notify Beta Users', 'CNT-NWS'),
      _n('n6', 780, 150, 'Re-Survey D30', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-086',
    category: 'PRODUCT',
    source: 'github',
    owner: 'INF-FS',
    name: 'Deprecation Manager',
    trigger: 'Feature Sunset Schedule',
    tags: ['deprecation', 'migration', 'sunset', 'communication'],
    desc: 'Sunset date set → identify active users → migration path gen → T-90 email → T-30 in-app warning → T-7 final alert → kill switch → verify.',
    nodes: [
      _n('n1', 60, 100, 'Sunset Schedule', 'INF-FS'),
      _n('n2', 240, 100, 'Identify Active Users', 'ARC-OPT'),
      _n('n3', 420, 100, 'Migration Path', 'ARC-FRG'),
      _n('n4', 600, 50, 'T-90 + T-30 Emails', 'CNT-NWS'),
      _n('n5', 600, 150, 'T-7 In-App Warn', 'INF-WEB'),
      _n('n6', 800, 100, 'Kill Switch + Verify', 'INF-FS'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },

  // ── PERSONAL (8) ──────────────────────────────────────────────────────────
  {
    id: 'TPL-087',
    category: 'PERSONAL',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'Morning Productivity Stack',
    trigger: 'Daily 05:30',
    tags: ['morning', 'routine', 'focus', 'productivity'],
    desc: '05:30: pull weather + news + markets + tasks → AI priority stack for day → block deep work windows → set focus mode → brief notification.',
    nodes: [
      _n('n1', 60, 100, '05:30 Trigger', 'ARC-OPT'),
      _n('n2', 240, 30, 'News + Markets', 'ARC-SCT'),
      _n('n3', 240, 100, 'Tasks + Calendar', 'ARC-OPT'),
      _n('n4', 240, 170, 'Weather + Health', 'ARC-OPT'),
      _n('n5', 480, 100, 'AI Priority Stack', 'ARC-FRG'),
      _n('n6', 680, 100, 'Focus Mode Brief', 'ARC-OPT'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n1', 'n4'],
      ['n2', 'n5'],
      ['n3', 'n5'],
      ['n4', 'n5'],
      ['n5', 'n6'],
    ),
  },
  {
    id: 'TPL-088',
    category: 'PERSONAL',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Health & Performance Tracker',
    trigger: 'Daily Wearable Sync',
    tags: ['health', 'HRV', 'sleep', 'performance', 'biometrics'],
    desc: 'Wearable sync → pull HRV + sleep + activity → performance score calc → trend analysis → AI readiness brief → adjust training load → log.',
    nodes: [
      _n('n1', 60, 100, 'Wearable Sync', 'ARC-OPT'),
      _n('n2', 240, 50, 'HRV + Sleep', 'ARC-OPT'),
      _n('n3', 240, 150, 'Activity + Nutrition', 'ARC-OPT'),
      _n('n4', 460, 100, 'Perf Score Calc', 'ARC-FRG'),
      _n('n5', 660, 100, 'Readiness Brief', 'ARC-OPT'),
      _n('n6', 820, 100, 'Adjust Load + Log', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-089',
    category: 'PERSONAL',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'Deep Work Scheduler',
    trigger: 'Daily Calendar Analysis',
    tags: ['deep-work', 'focus', 'calendar', 'time-blocking'],
    desc: 'Analyze calendar → identify 90-min deep work windows → protect from meetings → set Do Not Disturb → prepare context doc → end-session log.',
    nodes: [
      _n('n1', 60, 100, 'Calendar Analysis', 'ARC-OPT'),
      _n('n2', 240, 100, 'Find DW Windows', 'ARC-FRG'),
      _n('n3', 420, 100, 'Block + Protect', 'ARC-OPT'),
      _n('n4', 600, 50, 'Set DND Mode', 'ARC-OPT'),
      _n('n5', 600, 150, 'Prepare Context', 'ARC-FRG'),
      _n('n6', 800, 100, 'End Session Log', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-090',
    category: 'PERSONAL',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Continuous Learning Pipeline',
    trigger: 'Daily 21:00',
    tags: ['learning', 'Anki', 'spaced-repetition', 'books', 'courses'],
    desc: '21:00: pull reading queue + courses + papers → AI extract key concepts → generate Anki cards → schedule review → track knowledge graph → weekly report.',
    nodes: [
      _n('n1', 60, 100, '21:00 Trigger', 'ARC-OPT'),
      _n('n2', 240, 50, 'Reading Queue', 'ARC-SCT'),
      _n('n3', 240, 150, 'Courses + Papers', 'INF-WS'),
      _n('n4', 460, 100, 'Extract Concepts', 'ARC-FRG'),
      _n('n5', 660, 100, 'Anki Cards + Schedule', 'ARC-OPT'),
      _n('n6', 820, 100, 'Knowledge Graph', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-091',
    category: 'PERSONAL',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'Weekly Goal Review Engine',
    trigger: 'Sunday 19:00',
    tags: ['goals', 'OKR', 'review', 'planning', 'accountability'],
    desc: 'Sunday review: pull weekly goals + completed tasks → score progress → identify blockers → AI next-week plan → recalibrate priorities → journal.',
    nodes: [
      _n('n1', 60, 100, 'Sunday 19:00', 'ARC-OPT'),
      _n('n2', 240, 50, 'Pull Goals + Tasks', 'ARC-OPT'),
      _n('n3', 240, 150, 'Score Progress', 'ARC-OPT'),
      _n('n4', 460, 100, 'Identify Blockers', 'ARC-FRG'),
      _n('n5', 660, 100, 'Next Week Plan', 'ARC-FRG'),
      _n('n6', 820, 100, 'Recalibrate + Journal', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-092',
    category: 'PERSONAL',
    source: 'n8n',
    owner: 'FIN-TRD',
    name: 'Personal Finance Dashboard',
    trigger: 'Daily Bank Sync',
    tags: ['personal-finance', 'budget', 'net-worth', 'tracking'],
    desc: 'Daily sync → categorize transactions → vs budget delta → net worth calc → investment performance → tax estimate → alert on anomalies.',
    nodes: [
      _n('n1', 60, 100, 'Bank Sync', 'FIN-TRD'),
      _n('n2', 240, 100, 'Categorize Txns', 'ARC-FRG'),
      _n('n3', 420, 50, 'vs Budget Delta', 'FIN-TRD'),
      _n('n4', 420, 150, 'Net Worth Calc', 'FIN-TRD'),
      _n('n5', 640, 100, 'Tax Estimate', 'LGL-TAX'),
      _n('n6', 820, 100, 'Anomaly Alert', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-093',
    category: 'PERSONAL',
    source: 'n8n',
    owner: 'ARC-OPT',
    name: 'Network Intelligence Manager',
    trigger: 'Weekly Relationship Review',
    tags: ['networking', 'CRM', 'follow-up', 'relationships'],
    desc: 'Weekly review of relationship strength scores → identify who needs contact → AI personalized message draft → send reminder → log interaction.',
    nodes: [
      _n('n1', 60, 100, 'Weekly Review', 'ARC-OPT'),
      _n('n2', 240, 100, 'Relationship Scores', 'ARC-OPT'),
      _n('n3', 420, 100, 'Flag Needs Contact', 'ARC-SCT'),
      _n('n4', 600, 100, 'AI Draft Message', 'ARC-FRG'),
      _n('n5', 780, 100, 'Send Reminder + Log', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5']),
  },
  {
    id: 'TPL-094',
    category: 'PERSONAL',
    source: 'jarvis',
    owner: 'ARC-OPT',
    name: 'High-Stakes Decision Framework',
    trigger: 'Decision Input',
    tags: ['decision', 'second-order', 'pre-mortem', 'clarity'],
    desc: 'Input decision → AI map options + tradeoffs → second-order consequences → pre-mortem analysis → confidence score → pros/cons matrix → recommendation.',
    nodes: [
      _n('n1', 60, 100, 'Decision Input', 'ARC-OPT'),
      _n('n2', 240, 100, 'Map Options', 'ARC-FRG'),
      _n('n3', 420, 50, '2nd Order Effects', 'ARC-FRG'),
      _n('n4', 420, 150, 'Pre-Mortem', 'ARC-FRG'),
      _n('n5', 640, 100, 'Confidence Score', 'ARC-OPT'),
      _n('n6', 820, 100, 'Final Recommendation', 'ARC-FRG'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n2', 'n4'], ['n3', 'n5'], ['n4', 'n5'], ['n5', 'n6']),
  },

  // ── COMMUNITY (6) ─────────────────────────────────────────────────────────
  {
    id: 'TPL-095',
    category: 'COMMUNITY',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Discord Community Bot',
    trigger: 'Server Events · Continuous',
    tags: ['Discord', 'community', 'bot', 'moderation'],
    desc: 'Monitor server events → welcome new members → auto-role assign → detect spam/toxicity → escalate to mod → weekly server health report.',
    nodes: [
      _n('n1', 60, 100, 'Server Events', 'CNT-HUB'),
      _n('n2', 240, 50, 'Welcome + Role', 'CNT-HUB'),
      _n('n3', 240, 150, 'Spam/Toxicity Check', 'INF-HCK'),
      _n('n4', 460, 100, 'Escalate to Mod', 'CNT-HUB'),
      _n('n5', 660, 100, 'Mod Action', 'CNT-HUB'),
      _n('n6', 820, 100, 'Health Report', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n1', 'n3'], ['n2', 'n4'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-096',
    category: 'COMMUNITY',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Member Onboarding Flow',
    trigger: 'New Member Joins',
    tags: ['onboarding', 'community', 'engagement', 'activation'],
    desc: 'Join event → welcome DM + intro video → community tour thread → assign buddy → 48h check-in → first contribution nudge → track activation.',
    nodes: [
      _n('n1', 60, 100, 'Member Joins', 'CNT-HUB'),
      _n('n2', 240, 100, 'Welcome DM + Tour', 'CNT-HUB'),
      _n('n3', 420, 100, 'Assign Buddy', 'CNT-HUB'),
      _n('n4', 600, 100, '48h Check-In', 'CNT-HUB'),
      _n('n5', 780, 100, 'First Contribution', 'CNT-HUB'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5']),
  },
  {
    id: 'TPL-097',
    category: 'COMMUNITY',
    source: 'jarvis',
    owner: 'CNT-HUB',
    name: 'Community Event Automation',
    trigger: 'Event Creation',
    tags: ['events', 'community', 'live', 'registration'],
    desc: 'Event created → announcement sequence (T-7/T-3/T-1/day-of) → registration tracking → reminder DMs → live support bot → recording + recap post.',
    nodes: [
      _n('n1', 60, 100, 'Event Created', 'CNT-HUB'),
      _n('n2', 240, 100, 'Announcement Seq', 'CNT-HUB'),
      _n('n3', 420, 100, 'Registration Track', 'ARC-OPT'),
      _n('n4', 600, 50, 'Reminder DMs', 'CNT-HUB'),
      _n('n5', 600, 150, 'Live Support Bot', 'CNT-HUB'),
      _n('n6', 800, 100, 'Recording + Recap', 'CNT-HUB'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n3', 'n5'], ['n4', 'n6'], ['n5', 'n6']),
  },
  {
    id: 'TPL-098',
    category: 'COMMUNITY',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Ambassador Program Manager',
    trigger: 'Ambassador Application',
    tags: ['ambassador', 'advocacy', 'rewards', 'program'],
    desc: 'Application → score candidate → tier assignment → welcome kit → monthly missions assign → track completions → reward distribution → leaderboard.',
    nodes: [
      _n('n1', 60, 100, 'Application', 'CNT-HUB'),
      _n('n2', 240, 100, 'Score + Tier', 'ARC-OPT'),
      _n('n3', 420, 100, 'Welcome Kit', 'CNT-HUB'),
      _n('n4', 600, 50, 'Monthly Missions', 'CNT-HUB'),
      _n('n5', 600, 150, 'Track + Reward', 'ARC-OPT'),
      _n('n6', 800, 100, 'Leaderboard Update', 'CNT-HUB'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n5', 'n6']),
  },
  {
    id: 'TPL-099',
    category: 'COMMUNITY',
    source: 'jarvis',
    owner: 'CNT-HUB',
    name: 'Viral Challenge Engine',
    trigger: 'Challenge Launch',
    tags: ['challenge', 'UGC', 'viral', 'engagement'],
    desc: 'Launch challenge → announce across platforms → track submissions with hashtag → AI judge + score → daily leaderboard → winner announce → prize flow.',
    nodes: [
      _n('n1', 60, 100, 'Challenge Launch', 'CNT-HUB'),
      _n('n2', 240, 100, 'Cross-Platform Blast', 'CNT-HUB'),
      _n('n3', 420, 100, 'Track Submissions', 'ARC-SCT'),
      _n('n4', 600, 100, 'AI Judge + Score', 'ARC-FRG'),
      _n('n5', 780, 50, 'Leaderboard Update', 'CNT-HUB'),
      _n('n6', 780, 150, 'Winner + Prize', 'ARC-OPT'),
    ],
    edges: _e(['n1', 'n2'], ['n2', 'n3'], ['n3', 'n4'], ['n4', 'n5'], ['n4', 'n6']),
  },
  {
    id: 'TPL-100',
    category: 'COMMUNITY',
    source: 'n8n',
    owner: 'CNT-HUB',
    name: 'Community Health Pulse',
    trigger: 'Weekly Metrics Pull',
    tags: ['community', 'health', 'churn', 'DAU', 'sentiment'],
    desc: 'Weekly: pull DAU/MAU + message volume + sentiment + churn rate → health score calc → identify at-risk cohorts → engagement campaigns → exec brief.',
    nodes: [
      _n('n1', 60, 100, 'Weekly Pull', 'CNT-HUB'),
      _n('n2', 240, 50, 'DAU/MAU + Volume', 'ARC-OPT'),
      _n('n3', 240, 150, 'Sentiment Analysis', 'ARC-FRG'),
      _n('n4', 460, 100, 'Health Score Calc', 'ARC-OPT'),
      _n('n5', 660, 50, 'At-Risk Cohorts', 'ARC-OPT'),
      _n('n6', 660, 150, 'Engagement Campaigns', 'CNT-HUB'),
      _n('n7', 840, 100, 'Exec Brief', 'ARC-OPT'),
    ],
    edges: _e(
      ['n1', 'n2'],
      ['n1', 'n3'],
      ['n2', 'n4'],
      ['n3', 'n4'],
      ['n4', 'n5'],
      ['n4', 'n6'],
      ['n5', 'n7'],
      ['n6', 'n7'],
    ),
  },
];
