#!/usr/bin/env node
// @ts-nocheck
/**
 * IPC codegen (D4) — ironclad.
 *
 * Reads electron/ipc/registry.ts and writes:
 *   - docs/IPC.md
 *   - electron/ipc/generated/preload-channels.d.ts
 *   - electron/ipc/generated/preload-channel-map.ts
 *   - electron/ipc/generated/preload-invokes.ts  (nested jarvisBridge invoke stubs)
 *
 * `--check` fails when:
 *   - generated artifacts drift
 *   - any ipcMain.handle channel is missing from the registry
 *   - any registry channel lacks a handler in scanned files
 *   - any registry preloadKey channel is missing from preload.ts ∪ generated invokes
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const REGISTRY = resolve(ROOT, 'electron/ipc/registry.ts');
const OUT_MD = resolve(ROOT, 'docs/IPC.md');
const OUT_DTS = resolve(ROOT, 'electron/ipc/generated/preload-channels.d.ts');
const OUT_MAP = resolve(ROOT, 'electron/ipc/generated/preload-channel-map.ts');
const OUT_INV = resolve(ROOT, 'electron/ipc/generated/preload-invokes.ts');
const OUT_KEYS = resolve(ROOT, 'electron/ipc/generated/preload-bridge-keys.ts');
const GLOBAL_DTS = resolve(ROOT, 'src/global.d.ts');
const CHECK = process.argv.includes('--check');

function handlerGlobs() {
  const ipcDir = resolve(ROOT, 'electron/ipc');
  const registers = existsSync(ipcDir)
    ? readdirSync(ipcDir)
        .filter((f) => f.startsWith('register-') && f.endsWith('.ts'))
        .map((f) => `electron/ipc/${f}`)
    : [];
  return [
    'electron/main.ts',
    'electron/employees/ipc.ts',
    'electron/gateway/ipc.ts',
    'electron/harness/ipc.ts',
    ...registers,
  ];
}

/** @param {string} src */
function parseChannels(src) {
  const channels = [];
  const re =
    /\{\s*channel:\s*'([^']+)'\s*,\s*(?:preloadKey:\s*'([^']+)'\s*,\s*)?purpose:\s*'([^']*)'\s*,\s*risk:\s*'([ABCD])'\s*,\s*handler:\s*'([^']*)'\s*,?\s*\}/g;
  let m;
  while ((m = re.exec(src))) {
    channels.push({
      channel: m[1],
      preloadKey: m[2] || '',
      purpose: m[3],
      risk: m[4],
      handler: m[5],
    });
  }
  return channels;
}

/** @param {string} rel */
function scanHandlers(rel) {
  const abs = resolve(ROOT, rel);
  if (!existsSync(abs)) return new Set();
  const src = readFileSync(abs, 'utf8');
  const set = new Set();
  for (const m of src.matchAll(/ipcMain\.handle\(\s*['"]([^'"]+)['"]/g)) set.add(m[1]);
  return set;
}

function scanInvokes(abs) {
  if (!existsSync(abs)) return new Set();
  const src = readFileSync(abs, 'utf8');
  const set = new Set();
  for (const m of src.matchAll(/ipcRenderer\.invoke\(['"]([^'"]+)['"]/g)) set.add(m[1]);
  return set;
}

/**
 * Build nested object source from preloadKey paths.
 * @param {{ channel: string, preloadKey: string }[]} channels
 */
function renderPreloadInvokes(channels) {
  /** @type {Map<string, any>} */
  const tree = new Map();

  function ensure(map, key) {
    if (!map.has(key)) map.set(key, new Map());
    return map.get(key);
  }

  for (const c of channels.filter((x) => x.preloadKey)) {
    const parts = c.preloadKey.split('.');
    let cur = tree;
    for (let i = 0; i < parts.length - 1; i++) {
      cur = ensure(cur, parts[i]);
    }
    const leaf = parts[parts.length - 1];
    cur.set(leaf, c.channel);
  }

  /** @param {Map<string, any>} map @param {number} indent */
  function emit(map, indent) {
    const pad = '  '.repeat(indent);
    const lines = [];
    const keys = [...map.keys()].sort();
    for (const k of keys) {
      const v = map.get(k);
      if (typeof v === 'string') {
        lines.push(`${pad}${k}: (...args: unknown[]) => ipcRenderer.invoke('${v}', ...args),`);
      } else {
        lines.push(`${pad}${k}: {`);
        lines.push(...emit(v, indent + 1));
        lines.push(`${pad}},`);
      }
    }
    return lines;
  }

  return `/** Generated by pnpm gen:ipc — do not edit. */
import { ipcRenderer } from 'electron';

/**
 * Nested invoke stubs for every registry channel with a preloadKey.
 * Hand-written preload.ts deep-merges overrides (arg shaping / events) on top.
 */
export const GENERATED_PRELOAD_INVOKES = {
${emit(tree, 1).join('\n')}
} as const;

/** Flat list of channels this file exposes via ipcRenderer.invoke. */
export const GENERATED_PRELOAD_INVOKE_CHANNELS = [
${channels
  .filter((c) => c.preloadKey)
  .map((c) => c.channel)
  .sort()
  .map((n) => `  '${n}',`)
  .join('\n')}
] as const;
`;
}

/** @param {{ channel: string, preloadKey: string, purpose: string, risk: string, handler: string }[]} channels */
/** @param {{ handlersMissing: string[], preloadMissing: string[], registryOrphans: string[], handlerOnly: string[] }} drift */
function renderMarkdown(channels, drift) {
  const lines = [
    '# IPC channel registry',
    '',
    '> **Generated** by `pnpm gen:ipc` from `electron/ipc/registry.ts`.',
    '> Do not edit by hand — run `pnpm gen:ipc` after changing the registry.',
    '> CI: `pnpm gen:ipc --check` (ironclad: handlers ↔ registry ↔ preloadKey coverage).',
    '',
    '## Migration path',
    '',
    '1. Add a row to `CHANNELS` in `electron/ipc/registry.ts` when you add `ipcMain.handle`.',
    '2. Run `pnpm gen:ipc` — updates IPC.md, preload-channels.d.ts, preload-channel-map.ts, **preload-invokes.ts**.',
    '3. Wire handlers in `register*Ipc()` modules; bootstrap calls them from `main.ts`.',
    '4. `electron/preload.ts` merges `GENERATED_PRELOAD_INVOKES` with hand-written overrides (events + arg shaping).',
    '5. Employee channels without preloadKey stay main-only.',
    '',
    '## Drift status',
    '',
  ];

  const clean =
    drift.handlersMissing.length === 0 &&
    drift.preloadMissing.length === 0 &&
    drift.registryOrphans.length === 0;

  if (clean) {
    lines.push('✅ Registry covers all scanned handlers; every preloadKey channel is invoked in preload surface.');
  } else {
    if (drift.handlersMissing.length) {
      lines.push('### Handlers not in registry (CI fails)', '');
      for (const c of drift.handlersMissing) lines.push(`- \`${c}\``);
      lines.push('');
    }
    if (drift.registryOrphans.length) {
      lines.push('### Registry channels without handler (CI fails)', '');
      for (const c of drift.registryOrphans) lines.push(`- \`${c}\``);
      lines.push('');
    }
    if (drift.preloadMissing.length) {
      lines.push('### preloadKey channels missing from preload surface (CI fails)', '');
      for (const c of drift.preloadMissing) lines.push(`- \`${c}\``);
      lines.push('');
    }
  }

  if (drift.handlerOnly.length) {
    lines.push('### Registered without preloadKey (main/harness only — expected)', '');
    for (const c of drift.handlerOnly.slice(0, 40)) lines.push(`- \`${c}\``);
    if (drift.handlerOnly.length > 40) lines.push(`- … +${drift.handlerOnly.length - 40} more`);
    lines.push('');
  }

  lines.push(
    `## Channels (${channels.length})`,
    '',
    '| Channel | Preload | Risk | Purpose | Handler |',
    '|---|---|---|---|---|',
  );
  for (const c of channels) {
    lines.push(
      `| \`${c.channel}\` | ${c.preloadKey ? `\`${c.preloadKey}\`` : '—'} | ${c.risk} | ${c.purpose} | \`${c.handler}\` |`,
    );
  }
  lines.push(
    '',
    '## Risk legend',
    '',
    '- **A** — read-only / status',
    '- **B** — LLM / network egress',
    '- **C** — filesystem or config mutation',
    '- **D** — shell, trading, or privileged side effects',
    '',
  );
  return `${lines.join('\n')}\n`;
}

/** @param {{ channel: string, preloadKey: string }[]} channels */
function renderPreloadDts(channels) {
  const names = channels.map((c) => c.channel).sort();
  const union = names.map((n) => `  | '${n}'`).join('\n');
  return `/** Generated by pnpm gen:ipc — do not edit. */
/** Ambient channel union; runtime constants live in preload-channel-map.ts */
export type RegistryIpcChannel =
${union};
`;
}

/** @param {{ channel: string, preloadKey: string }[]} channels */
function renderPreloadMap(channels) {
  const withKey = channels
    .filter((c) => c.preloadKey)
    .slice()
    .sort((a, b) => a.channel.localeCompare(b.channel));
  const entries = withKey.map((c) => `  '${c.channel}': '${c.preloadKey}',`).join('\n');
  const all = channels
    .map((c) => c.channel)
    .sort()
    .map((n) => `  '${n}',`)
    .join('\n');

  return `/** Generated by pnpm gen:ipc — do not edit. */
import type { RegistryIpcChannel } from './preload-channels';

export const REGISTRY_IPC_CHANNELS = [
${all}
] as const satisfies readonly RegistryIpcChannel[];

/** channel → jarvisBridge property path (dot-nested keys as string). */
export const PRELOAD_CHANNEL_MAP = {
${entries}
} as const satisfies Readonly<Partial<Record<RegistryIpcChannel, string>>>;
`;
}

function fingerprint(text) {
  return createHash('sha256').update(text).digest('hex');
}

/** @param {{ channel: string, preloadKey: string }[]} channels */
function renderBridgeKeys(channels) {
  const keys = channels
    .filter((c) => c.preloadKey)
    .map((c) => c.preloadKey)
    .sort();
  return `/** Generated by pnpm gen:ipc — do not edit. */
/** Dot-paths on window.jarvisBridge that must exist in src/global.d.ts (D4 drift lock). */
export const GENERATED_PRELOAD_BRIDGE_KEYS = [
${keys.map((k) => `  '${k}',`).join('\n')}
] as const;

export type GeneratedPreloadBridgeKey = (typeof GENERATED_PRELOAD_BRIDGE_KEYS)[number];
`;
}

/**
 * Fail if any registry preloadKey leaf is absent from src/global.d.ts jarvisBridge surface.
 * @param {{ preloadKey: string }[]} channels
 * @param {string} globalSrc
 */
function checkGlobalDtsCoverage(channels, globalSrc) {
  const missing = [];
  for (const c of channels.filter((x) => x.preloadKey)) {
    const parts = c.preloadKey.split('.');
    const leaf = parts[parts.length - 1];
    // Property declaration or method-ish: `leaf:` / `leaf?:` / `leaf(` / `leaf ?(`
    const leafRe = new RegExp(`\\b${leaf}\\s*(\\??\\s*:|\\()`);
    if (!leafRe.test(globalSrc)) {
      missing.push(c.preloadKey);
    }
  }
  return missing;
}

/**
 * Hand-written ipcRenderer.invoke channels in preload.ts must be registry members
 * (generated invokes are checked separately via artifact fingerprint).
 */
function checkPreloadHandInvokesInRegistry(preloadSrc, registryNames) {
  const hand = [...preloadSrc.matchAll(/ipcRenderer\.invoke\(['"]([^'"]+)['"]/g)].map((m) => m[1]);
  return [...new Set(hand)].filter((ch) => !registryNames.has(ch)).sort();
}


function checkFile(path, expected) {
  if (!existsSync(path)) {
    console.error(`gen-ipc --check: missing ${path} — run pnpm gen:ipc`);
    return false;
  }
  const existing = readFileSync(path, 'utf8');
  if (fingerprint(existing) !== fingerprint(expected)) {
    console.error(`gen-ipc --check: ${path} is out of date — run pnpm gen:ipc`);
    return false;
  }
  return true;
}

function main() {
  if (!existsSync(REGISTRY)) {
    console.error(`gen-ipc: missing ${REGISTRY}`);
    return 1;
  }
  const src = readFileSync(REGISTRY, 'utf8');
  const channels = parseChannels(src);
  if (channels.length === 0) {
    console.error('gen-ipc: parsed 0 channels — registry format changed?');
    return 1;
  }

  const registryNames = new Set(channels.map((c) => c.channel));
  const allHandlers = new Set();
  for (const f of handlerGlobs()) {
    for (const h of scanHandlers(f)) allHandlers.add(h);
  }

  const preloadPath = resolve(ROOT, 'electron/preload.ts');
  const preloadInvokes = new Set([
    ...scanInvokes(preloadPath),
    ...scanInvokes(OUT_INV),
  ]);

  const handlersMissing = [...allHandlers].filter((h) => !registryNames.has(h)).sort();
  const registryOrphans = [...registryNames].filter((n) => !allHandlers.has(n)).sort();
  const preloadMissing = channels
    .filter((c) => c.preloadKey)
    .map((c) => c.channel)
    .filter((c) => {
      if (CHECK) return !preloadInvokes.has(c);
      return false;
    })
    .sort();

  // After write, also verify preload.ts imports GENERATED_PRELOAD_INVOKES when --check
  let preloadImportOk = true;
  if (CHECK) {
    const preloadSrc = readFileSync(preloadPath, 'utf8');
    if (!preloadSrc.includes('GENERATED_PRELOAD_INVOKES')) {
      console.error('gen-ipc --check: electron/preload.ts must import GENERATED_PRELOAD_INVOKES');
      preloadImportOk = false;
    }
    // Recompute preload missing assuming generated file content is what we expect
    const expectedInv = renderPreloadInvokes(channels);
    const expectedChannels = new Set([
      ...scanInvokes(preloadPath),
      ...[...expectedInv.matchAll(/ipcRenderer\.invoke\('([^']+)'/g)].map((m) => m[1]),
    ]);
    for (const c of channels.filter((x) => x.preloadKey)) {
      if (!expectedChannels.has(c.channel) && !preloadInvokes.has(c.channel)) {
        // will be caught if generated out of date; if generated matches, generated covers
      }
    }
  }

  const handlerOnly = [...registryNames]
    .filter((n) => !channels.find((c) => c.channel === n)?.preloadKey)
    .sort();

  const drift = { handlersMissing, preloadMissing: [], registryOrphans, handlerOnly };
  // After generation, preload-invokes covers all preloadKeys; --check validates the union.
  const md = renderMarkdown(channels, drift);
  const dts = renderPreloadDts(channels);
  const mapTs = renderPreloadMap(channels);
  const invTs = renderPreloadInvokes(channels);
  const keysTs = renderBridgeKeys(channels);

  const hardFail =
    handlersMissing.length > 0 || registryOrphans.length > 0 || (CHECK && preloadMissing.length > 0);

  if (hardFail) {
    console.error('gen-ipc: registry drift detected:');
    if (handlersMissing.length)
      console.error(`  handlers missing from registry: ${handlersMissing.join(', ')}`);
    if (registryOrphans.length)
      console.error(`  registry without handler: ${registryOrphans.join(', ')}`);
    if (CHECK && preloadMissing.length)
      console.error(`  preloadKey missing from preload surface: ${preloadMissing.join(', ')}`);
    if (!CHECK) console.error('  fix handlers/registry then re-run pnpm gen:ipc');
    if (CHECK) return 1;
  }

  if (CHECK) {
    const mdOk = checkFile(OUT_MD, md);
    const dtsOk = checkFile(OUT_DTS, dts);
    const mapOk = checkFile(OUT_MAP, mapTs);
    const invOk = checkFile(OUT_INV, invTs);
    const keysOk = checkFile(OUT_KEYS, keysTs);
    if (!mdOk || !dtsOk || !mapOk || !invOk || !keysOk || !preloadImportOk) return 1;

    // Final: union of preload.ts + generated must cover every preloadKey
    const union = new Set([...scanInvokes(preloadPath), ...scanInvokes(OUT_INV)]);
    const stillMissing = channels
      .filter((c) => c.preloadKey && !union.has(c.channel))
      .map((c) => c.channel);
    if (stillMissing.length) {
      console.error(`gen-ipc --check: preloadKey not covered: ${stillMissing.join(', ')}`);
      return 1;
    }

    if (!existsSync(GLOBAL_DTS)) {
      console.error('gen-ipc --check: missing src/global.d.ts');
      return 1;
    }
    const globalSrc = readFileSync(GLOBAL_DTS, 'utf8');
    const globalMissing = checkGlobalDtsCoverage(channels, globalSrc);
    if (globalMissing.length) {
      console.error(
        `gen-ipc --check: global.d.ts missing jarvisBridge keys for: ${globalMissing.join(', ')}`,
      );
      return 1;
    }

    const preloadSrc = readFileSync(preloadPath, 'utf8');
    const handOrphans = checkPreloadHandInvokesInRegistry(preloadSrc, registryNames);
    if (handOrphans.length) {
      console.error(
        `gen-ipc --check: preload.ts invokes not in registry: ${handOrphans.join(', ')}`,
      );
      return 1;
    }

    console.log(
      `gen-ipc --check: ok (${channels.length} channels, ${allHandlers.size} handlers, preloadKey + global.d.ts ironclad)`,
    );
    return 0;
  }

  mkdirSync(dirname(OUT_MD), { recursive: true });
  mkdirSync(dirname(OUT_DTS), { recursive: true });
  writeFileSync(OUT_MD, md, 'utf8');
  writeFileSync(OUT_DTS, dts, 'utf8');
  writeFileSync(OUT_MAP, mapTs, 'utf8');
  writeFileSync(OUT_INV, invTs, 'utf8');
  writeFileSync(OUT_KEYS, keysTs, 'utf8');
  console.log(
    `gen-ipc: wrote IPC.md + preload-channels.d.ts + preload-channel-map.ts + preload-invokes.ts + preload-bridge-keys.ts (${channels.length} channels)`,
  );
  return 0;
}

process.exit(main());
