/**
 * IPC channel registry — single source of truth for contract codegen (D4).
 *
 * `scripts/gen-ipc.mjs` turns this into `docs/IPC.md`,
 * `electron/ipc/generated/preload-channels.d.ts`, and
 * `electron/ipc/generated/preload-channel-map.ts`. Run `pnpm gen:ipc` after edits.
 * Still hand-written: `electron/preload.ts`, `src/global.d.ts`.
 *
 * Migration path:
 *   1. Add a row when you add/touch an `ipcMain.handle`.
 *   2. `pnpm gen:ipc` updates generated artifacts; `pnpm gen:ipc --check` fails CI on drift.
 *   3. Move handler wiring into `register*Ipc()` modules (see `ipc/register-config.ts`).
 *   4. Remaining inline handlers in `main.ts` — migrate incrementally; see docs/IPC.md § Drift.
 */
// @ts-nocheck

export type IpcRisk = 'A' | 'B' | 'C' | 'D';

export interface IpcChannelDef {
  channel: string;
  preloadKey?: string;
  purpose: string;
  risk: IpcRisk;
  handler: string;
}

export const CHANNELS: readonly IpcChannelDef[] = [
  {
    channel: 'app:notify',
    preloadKey: 'notify',
    purpose: 'app · notify',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'apps:add',
    preloadKey: 'appsAdd',
    purpose: 'apps · add',
    risk: 'C',
    handler: 'electron/main.ts',
  },
  {
    channel: 'apps:launch',
    preloadKey: 'appsLaunch',
    purpose: 'apps · launch',
    risk: 'D',
    handler: 'electron/main.ts',
  },
  {
    channel: 'apps:list',
    preloadKey: 'appsList',
    purpose: 'apps · list',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'apps:pick',
    preloadKey: 'appsPick',
    purpose: 'apps · pick',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'apps:remove',
    preloadKey: 'appsRemove',
    purpose: 'apps · remove',
    risk: 'C',
    handler: 'electron/main.ts',
  },
  {
    channel: 'apps:scan-common',
    preloadKey: 'appsScanCommon',
    purpose: 'apps · scan-common',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'browser:install',
    preloadKey: 'browser.install',
    purpose: 'browser · install',
    risk: 'C',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'browser:start',
    preloadKey: 'browser.start',
    purpose: 'browser · start',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'browser:status',
    preloadKey: 'browser.status',
    purpose: 'browser · status',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'commerce:sync',
    preloadKey: 'commerce.sync',
    purpose: 'Shopify catalog/orders via Composio tool slugs',
    risk: 'B',
    handler: 'electron/ipc/register-commerce.ts',
  },
  {
    channel: 'composio:catalog',
    preloadKey: 'composio.catalog',
    purpose: 'composio · catalog',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'composio:connections',
    preloadKey: 'composio.connections',
    purpose: 'composio · connections',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'composio:execute',
    preloadKey: 'composio.execute',
    purpose: 'composio · execute',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'composio:has',
    preloadKey: 'composio.has',
    purpose: 'composio · has',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'composio:initiate',
    preloadKey: 'composio.initiate',
    purpose: 'composio · initiate',
    risk: 'B',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'config:deleteKey',
    preloadKey: 'config.deleteKey',
    purpose: 'config · deleteKey',
    risk: 'C',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:getAdvancedMode',
    preloadKey: 'config.getAdvancedMode',
    purpose: 'config · getAdvancedMode',
    risk: 'A',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:getKey',
    preloadKey: 'config.getKey',
    purpose: 'config · getKey',
    risk: 'A',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:getMt5',
    preloadKey: 'config.getMt5',
    purpose: 'config · getMt5',
    risk: 'A',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:hasKey',
    preloadKey: 'config.hasKey',
    purpose: 'config · hasKey',
    risk: 'A',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:reload-keys',
    preloadKey: 'config.reloadKeys',
    purpose: 'config · reload-keys',
    risk: 'B',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:setAdvancedMode',
    preloadKey: 'config.setAdvancedMode',
    purpose: 'config · setAdvancedMode',
    risk: 'C',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:setKey',
    preloadKey: 'config.setKey',
    purpose: 'config · setKey',
    risk: 'C',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:setMt5',
    preloadKey: 'config.setMt5',
    purpose: 'config · setMt5',
    risk: 'C',
    handler: 'electron/ipc/register-config.ts',
  },
  {
    channel: 'config:test-provider',
    preloadKey: 'testProvider',
    purpose: 'config · test-provider',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'content:publish',
    preloadKey: 'content.publish',
    purpose: 'Cross-platform publish gate — live X when OAuth1 keys present',
    risk: 'B',
    handler: 'electron/ipc/register-content.ts',
  },
  {
    channel: 'console:runCmd',
    preloadKey: 'consoleRun',
    purpose: 'console · runCmd',
    risk: 'D',
    handler: 'electron/main.ts',
  },
  {
    channel: 'employee:calendar-propose',
    purpose: 'employee · calendar-propose',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:calendar-status',
    purpose: 'employee · calendar-status',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:email-classify',
    purpose: 'employee · email-classify',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:email-draft',
    purpose: 'employee · email-draft',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:email-fetch-inbox',
    preloadKey: 'employees.emailFetchInbox',
    purpose: 'IMAP fetch + rule-based classify when imapflow + creds present',
    risk: 'B',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:email-imap-status',
    purpose: 'employee · email-imap-status',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:invoice-extract',
    purpose: 'employee · invoice-extract',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:invoice-extract-path',
    purpose: 'employee · invoice-extract-path',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:invoice-preview',
    purpose: 'employee · invoice-preview',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:shop-list',
    purpose: 'employee · shop-list',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:shop-refund-draft',
    purpose: 'employee · shop-refund-draft',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'employee:shop-social-draft',
    purpose: 'employee · shop-social-draft',
    risk: 'C',
    handler: 'electron/employees/ipc.ts',
  },
  {
    channel: 'gateway:config-get',
    preloadKey: 'gateway.configGet',
    purpose: 'gateway · config-get',
    risk: 'A',
    handler: 'electron/gateway/ipc.ts',
  },
  {
    channel: 'gateway:config-set',
    preloadKey: 'gateway.configSet',
    purpose: 'gateway · config-set',
    risk: 'C',
    handler: 'electron/gateway/ipc.ts',
  },
  {
    channel: 'gateway:deliver',
    preloadKey: 'gateway.deliver',
    purpose: 'gateway · deliver',
    risk: 'A',
    handler: 'electron/gateway/ipc.ts',
  },
  {
    channel: 'gateway:start',
    preloadKey: 'gateway.start',
    purpose: 'gateway · start',
    risk: 'C',
    handler: 'electron/gateway/ipc.ts',
  },
  {
    channel: 'gateway:status',
    preloadKey: 'gateway.status',
    purpose: 'gateway · status',
    risk: 'A',
    handler: 'electron/gateway/ipc.ts',
  },
  {
    channel: 'gateway:stop',
    preloadKey: 'gateway.stop',
    purpose: 'gateway · stop',
    risk: 'A',
    handler: 'electron/gateway/ipc.ts',
  },
  {
    channel: 'harness:bench-smoke',
    preloadKey: 'harness.benchSmoke',
    purpose: 'harness · bench-smoke',
    risk: 'A',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'harness:hitl-pending',
    preloadKey: 'harness.hitlPending',
    purpose: 'harness · hitl-pending',
    risk: 'A',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'harness:hitl-resolve',
    preloadKey: 'harness.hitlResolve',
    purpose: 'harness · hitl-resolve',
    risk: 'A',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'harness:memory-search',
    preloadKey: 'harness.memorySearch',
    purpose: 'harness · memory-search',
    risk: 'A',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'harness:refine',
    preloadKey: 'harness.refine',
    purpose: 'harness · refine',
    risk: 'C',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'harness:run',
    preloadKey: 'harness.run',
    purpose: 'harness · run',
    risk: 'C',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'harness:status',
    preloadKey: 'harness.status',
    purpose: 'harness · status',
    risk: 'A',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'harness:swarm-plan',
    preloadKey: 'harness.swarmPlan',
    purpose: 'harness · swarm-plan',
    risk: 'A',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'harness:weekly-run',
    preloadKey: 'harness.weeklyRun',
    purpose: 'harness · weekly-run',
    risk: 'A',
    handler: 'electron/harness/ipc.ts',
  },
  {
    channel: 'jarvis:activate-vault-agents',
    preloadKey: 'activateVaultAgents',
    purpose: 'jarvis · activate-vault-agents',
    risk: 'C',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'jarvis:complete',
    preloadKey: 'complete',
    purpose: 'jarvis · complete',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:complete-stream',
    preloadKey: 'completeStream',
    purpose: 'jarvis · complete-stream',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:free-transcribe',
    preloadKey: 'freeTranscribe',
    purpose: 'jarvis · free-transcribe',
    risk: 'B',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'jarvis:gemini',
    preloadKey: 'geminiComplete',
    purpose: 'jarvis · gemini',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:gemini-audio',
    preloadKey: 'geminiAudio',
    purpose: 'jarvis · gemini-audio',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:gemini-transcribe',
    purpose: 'jarvis · gemini-transcribe',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:get-vault-paths',
    preloadKey: 'getVaultPaths',
    purpose: 'jarvis · get-vault-paths',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'jarvis:github',
    preloadKey: 'githubComplete',
    purpose: 'jarvis · github',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:has-gemini',
    preloadKey: 'hasGemini',
    purpose: 'jarvis · has-gemini',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:has-github',
    preloadKey: 'hasGithub',
    purpose: 'jarvis · has-github',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:has-key',
    preloadKey: 'hasKey',
    purpose: 'jarvis · has-key',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:has-ollama',
    preloadKey: 'hasOllama',
    purpose: 'jarvis · has-ollama',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:has-qwen',
    preloadKey: 'hasQwen',
    purpose: 'jarvis · has-qwen',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:live-scan',
    preloadKey: 'liveScan',
    purpose: 'jarvis · live-scan',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:ollama',
    preloadKey: 'ollamaComplete',
    purpose: 'jarvis · ollama',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:ollama-transcribe',
    preloadKey: 'ollamaTranscribe',
    purpose: 'jarvis · ollama-transcribe',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:qwen',
    preloadKey: 'qwenComplete',
    purpose: 'jarvis · qwen',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:read-file-content',
    preloadKey: 'readFileContent',
    purpose: 'jarvis · read-file-content',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:rebuild-index',
    preloadKey: 'rebuildIndex',
    purpose: 'jarvis · rebuild-index',
    risk: 'C',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:recent-activity',
    preloadKey: 'recentActivity',
    purpose: 'jarvis · recent-activity',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:scan-agents',
    preloadKey: 'scanAgents',
    purpose: 'jarvis · scan-agents',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:set-agents-path',
    preloadKey: 'setAgentsPath',
    purpose: 'jarvis · set-agents-path',
    risk: 'C',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'jarvis:system-selftest',
    preloadKey: 'systemSelfTest',
    purpose: 'jarvis · system-selftest',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'jarvis:voice-diag',
    preloadKey: 'voiceDiag',
    purpose: 'jarvis · voice-diag',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:voice-selftest',
    preloadKey: 'voiceSelfTest',
    purpose: 'jarvis · voice-selftest',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'jarvis:voice-session',
    preloadKey: 'voiceSession',
    purpose: 'jarvis · voice-session',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'jarvis:workspace',
    preloadKey: 'workspace',
    purpose: 'jarvis · workspace',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'jarvis:write-file',
    preloadKey: 'writeFile',
    purpose: 'jarvis · write-file',
    risk: 'C',
    handler: 'electron/main.ts',
  },
  {
    channel: 'memory:embed-search',
    preloadKey: 'memory.embedSearch',
    purpose: 'memory · embed-search',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'memory:embed-upsert',
    preloadKey: 'memory.embedUpsert',
    purpose: 'memory · embed-upsert',
    risk: 'C',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'mt5:start-bridge',
    preloadKey: 'startBridge',
    purpose: 'mt5 · start-bridge',
    risk: 'C',
    handler: 'electron/main.ts',
  },
  {
    channel: 'production:audit-trail',
    preloadKey: 'production.auditTrail',
    purpose: 'production · audit-trail',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:check-updates',
    preloadKey: 'production.checkUpdates',
    purpose: 'production · check-updates',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:crash-dumps-path',
    preloadKey: 'production.crashDumpsPath',
    purpose: 'production · crash-dumps-path',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:download-update',
    preloadKey: 'production.downloadUpdate',
    purpose: 'production · download-update',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:dry-run',
    preloadKey: 'production.dryRun',
    purpose: 'production · dry-run',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:employee-execute',
    preloadKey: 'production.employeeExecute',
    purpose: 'production · employee-execute',
    risk: 'D',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:employee-health',
    preloadKey: 'production.employeeHealth',
    purpose: 'production · employee-health',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:error-budget',
    preloadKey: 'production.errorBudget',
    purpose: 'production · error-budget',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:export-config',
    preloadKey: 'production.exportConfig',
    purpose: 'production · export-config',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:flags',
    preloadKey: 'production.flags',
    purpose: 'production · flags',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:imap-idle-status',
    preloadKey: 'production.imapIdleStatus',
    purpose: 'production · imap-idle-status',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:install-update',
    preloadKey: 'production.installUpdate',
    purpose: 'production · install-update',
    risk: 'D',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:kill-switch',
    preloadKey: 'production.killSwitch',
    purpose: 'production · kill-switch',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:record-voice-latency',
    preloadKey: 'production.recordVoiceLatency',
    purpose: 'production · record-voice-latency',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'production:setFlag',
    preloadKey: 'production.setFlag',
    purpose: 'production · setFlag',
    risk: 'A',
    handler: 'electron/ipc/register-production.ts',
  },
  {
    channel: 'search:web',
    preloadKey: 'searchWeb',
    purpose: 'search · web',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'shell:openExternal',
    preloadKey: 'shell.openExternal',
    purpose: 'shell · openExternal',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'social:post-ig',
    preloadKey: 'postToInstagram',
    purpose: 'social · post-ig',
    risk: 'D',
    handler: 'electron/main.ts',
  },
  {
    channel: 'social:post-x',
    preloadKey: 'postToX',
    purpose: 'social · post-x',
    risk: 'D',
    handler: 'electron/main.ts',
  },
  {
    channel: 'system:clearTemp',
    preloadKey: 'systemTools.clearTemp',
    purpose: 'system · clearTemp',
    risk: 'D',
    handler: 'electron/main.ts',
  },
  {
    channel: 'system:fileSearch',
    preloadKey: 'systemTools.fileSearch',
    purpose: 'system · fileSearch',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'system:getProcs',
    preloadKey: 'systemTools.getProcs',
    purpose: 'system · getProcs',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'system:memReduce',
    preloadKey: 'systemTools.memReduce',
    purpose: 'system · memReduce',
    risk: 'D',
    handler: 'electron/main.ts',
  },
  {
    channel: 'system:metrics',
    preloadKey: 'systemMetrics',
    purpose: 'system · metrics',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'system:netScan',
    preloadKey: 'systemTools.netScan',
    purpose: 'system · netScan',
    risk: 'B',
    handler: 'electron/main.ts',
  },
  {
    channel: 'system:openTool',
    preloadKey: 'systemTools.openTool',
    purpose: 'system · openTool',
    risk: 'D',
    handler: 'electron/main.ts',
  },
  {
    channel: 'trading:ccxt-ohlcv',
    preloadKey: 'trading.ccxtOhlcv',
    purpose: 'trading · ccxt-ohlcv',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'trading:ccxt-status',
    preloadKey: 'trading.ccxtStatus',
    purpose: 'trading · ccxt-status',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'trading:ccxt-ticker',
    preloadKey: 'trading.ccxtTicker',
    purpose: 'trading · ccxt-ticker',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'trading:econ-calendar',
    preloadKey: 'trading.econCalendar',
    purpose: 'trading · econ-calendar',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'trading:in-news-window',
    preloadKey: 'trading.inNewsWindow',
    purpose: 'trading · in-news-window',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'trading:journal-add',
    preloadKey: 'trading.journalAdd',
    purpose: 'trading · journal-add',
    risk: 'C',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'trading:journal-list',
    preloadKey: 'trading.journalList',
    purpose: 'trading · journal-list',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'trading:journal-weekly',
    preloadKey: 'trading.journalWeekly',
    purpose: 'trading · journal-weekly',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'voice:pickFiles',
    preloadKey: 'voicePickFiles',
    purpose: 'voice · pickFiles',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'voice:piper-speak',
    preloadKey: 'voice.piperSpeak',
    purpose: 'voice · piper-speak',
    risk: 'B',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'voice:piper-status',
    preloadKey: 'voice.piperStatus',
    purpose: 'voice · piper-status',
    risk: 'A',
    handler: 'electron/ipc/register-domain.ts',
  },
  {
    channel: 'workflow:cancel',
    preloadKey: 'workflowCancel',
    purpose: 'workflow · cancel',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'workflow:list-scheduled',
    preloadKey: 'workflowListScheduled',
    purpose: 'workflow · list-scheduled',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'workflow:schedule',
    preloadKey: 'workflowSchedule',
    purpose: 'workflow · schedule',
    risk: 'A',
    handler: 'electron/main.ts',
  },
  {
    channel: 'zeus:mt5',
    preloadKey: 'mt5',
    purpose: 'zeus · mt5',
    risk: 'D',
    handler: 'electron/main.ts',
  },
  {
    channel: 'zeus:ping',
    preloadKey: 'zeusPing',
    purpose: 'zeus · ping',
    risk: 'D',
    handler: 'electron/main.ts',
  },
] as const;

export const CHANNEL_BY_NAME = Object.fromEntries(CHANNELS.map((c) => [c.channel, c])) as Record<
  string,
  IpcChannelDef
>;
